

INSERT  INTO dbo.SystemConfigurationKeys
        ( 
         CreatedBy
        ,CreateDate
        ,ModifiedBy
        ,ModifiedDate
        ,[Key]
        ,Value
        ,Description
        ,AcceptedValues
        ,ShowKeyForViewingAndEditing
        ,Modules
        ,Screens
        ,Comments
        )
        SELECT  'dknewtson'  -- CreatedBy - type_CurrentUser
               ,GETDATE()-- CreateDate - type_CurrentDatetime
               ,'dknewtson'-- ModifiedBy - type_CurrentUser
               ,GETDATE()-- ModifiedDate - type_CurrentDatetime
               ,'ELECTRONICREMITTANCELOCATION'-- Key - varchar(200)
               ,NULL-- Value - varchar(max)
               ,'Payment Location for Payments generated by 835 Upload'-- Description - type_Comment2
               ,'GlobalCodeId Category FINANCIALLOCATION'-- AcceptedValues - varchar(max)
               ,'Y'-- ShowKeyForViewingAndEditing - type_YOrN
               ,'835'-- Modules - varchar(500)
               ,'Payments/Adjustments'-- Screens - varchar(500)
               ,NULL-- Comments - type_Comment2
        --FROM    dbo.GlobalCodes gc
        --WHERE   gc.Category = 'FINANCIALLOCATION'
        --        AND gc.CodeName = 'Patient Accounting'
        --        AND NOT EXISTS ( SELECT 1
        --                         FROM   dbo.SystemConfigurationKeys sck
        --                         WHERE  sck.[Key] = 'ELECTRONICREMITTANCELOCATION' )


                                 
