IF NOT EXISTS (SELECT * FROM dbo.GlobalCodeCategories WHERE Category = 'ImmunizationAdmSite') 
BEGIN 
	INSERT INTO dbo.GlobalCodeCategories ( Category, CategoryName, Active, AllowAddDelete, AllowCodeNameEdit, AllowSortOrderEdit, Description, UserDefinedCategory, HasSubcodes, UsedInPracticeManagement, UsedInCareManagement) 
	VALUES('ImmunizationAdmSite','Immunization Admin Site','Y','Y','N','N',NULL,'N','N','N','Y') 
END

IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Left Arm' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('ImmunizationAdmSite','Left Arm','Left Arm',NULL,'Y','N',1,'LA') END ELSE BEGIN UPDATE GlobalCodes  set Code='Left Arm',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',ExternalCode1='LA' Where Category='ImmunizationAdmSite' and CodeName='Left Arm' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Left Deltoid' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationAdmSite','Left Deltoid','Left Deltoid',NULL,'Y','Y',2,'LD','HL70163') END ELSE BEGIN UPDATE GlobalCodes  set Code='Left Deltoid',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',ExternalCode1='LD', ExternalCode2='HL70163' Where Category='ImmunizationAdmSite' and CodeName='Left Deltoid' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Left Thigh' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationAdmSite','Left Thigh','Left Thigh',NULL,'Y','Y',3,'LT','HL70163') END ELSE BEGIN UPDATE GlobalCodes  set Code='Left Thigh',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',ExternalCode1='LT', ExternalCode2='HL70163' Where Category='ImmunizationAdmSite' and CodeName='Left Thigh' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Right Arm' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('ImmunizationAdmSite','Right Arm','Right Arm',NULL,'Y','N',4,'RA') END ELSE BEGIN UPDATE GlobalCodes  set Code='Right Arm',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',ExternalCode1='RA' Where Category='ImmunizationAdmSite' and CodeName='Right Arm' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Right Deltoid' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationAdmSite','Right Deltoid','Right Deltoid',NULL,'Y','Y',5,'RD','HL70163') END ELSE BEGIN UPDATE GlobalCodes  set Code='Right Deltoid',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',ExternalCode1='RD', ExternalCode2='HL70163' Where Category='ImmunizationAdmSite' and CodeName='Right Deltoid' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Right Thigh' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationAdmSite','Right Thigh','Right Thigh',NULL,'Y','Y',6,'RT','HL70163') END ELSE BEGIN UPDATE GlobalCodes  set Code='Right Thigh',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',ExternalCode1='RT', ExternalCode2='HL70163' Where Category='ImmunizationAdmSite' and CodeName='Right Thigh' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationAdmSite' and CodeName='Unknown' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder) values('ImmunizationAdmSite','Unknown','Unknown',NULL,'Y','N',7) END ELSE BEGIN UPDATE GlobalCodes  set Code='Unknown',Description=NULL,Active='Y',CannotModifyNameOrDelete='N' Where Category='ImmunizationAdmSite' and CodeName='Unknown' END 
