IF NOT EXISTS (SELECT * FROM dbo.GlobalCodeCategories WHERE Category = 'VaccineFunding') 
BEGIN 
	INSERT INTO dbo.GlobalCodeCategories ( Category, CategoryName, Active, AllowAddDelete, AllowCodeNameEdit, AllowSortOrderEdit, Description, UserDefinedCategory, HasSubcodes, UsedInPracticeManagement, UsedInCareManagement) 
	VALUES('VaccineFunding','VaccineFunding','Y','Y','Y','Y',NULL,'N','N','N','N') 
END

IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='Medicaid' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','Medicaid','Medicaid',NULL,'Y','Y',1,'H02','') END ELSE BEGIN UPDATE GlobalCodes  set Code='Medicaid',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=1, ExternalCode1='H02', ExternalCode2='' Where Category='VaccineFunding' and CodeName='Medicaid' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='S-CHIP coverage-combination of Medicaid and separate-not VFC eligible' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','S-CHIP coverage-combination of Medicaid and separate-not VFC eligible','SCHIPMSNotVFCEligible',NULL,'Y','Y',2,'CH02','') END ELSE BEGIN UPDATE GlobalCodes  set Code='SCHIPMSNotVFCEligible',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=2, ExternalCode1='CH02', ExternalCode2='' Where Category='VaccineFunding' and CodeName='S-CHIP coverage-combination of Medicaid and separate-not VFC eligible' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='S-CHIP coverage-not VFC eligible' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','S-CHIP coverage-not VFC eligible','SCHIPNotVFCEligible',NULL,'Y','Y',3,'CH00','') END ELSE BEGIN UPDATE GlobalCodes  set Code='SCHIPNotVFCEligible',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=3, ExternalCode1='CH00', ExternalCode2='' Where Category='VaccineFunding' and CodeName='S-CHIP coverage-not VFC eligible' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='S-CHIP coverage-separate from Medicaid-not VFC eligible' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','S-CHIP coverage-separate from Medicaid-not VFC eligible','SCHIPMedicaidNotVFCEligible',NULL,'Y','Y',4,'CH01','') END ELSE BEGIN UPDATE GlobalCodes  set Code='SCHIPMedicaidNotVFCEligible',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=4, ExternalCode1='CH01', ExternalCode2='' Where Category='VaccineFunding' and CodeName='S-CHIP coverage-separate from Medicaid-not VFC eligible' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='Self pay' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','Self pay','SelfPay',NULL,'Y','Y',0,'H01','') END ELSE BEGIN UPDATE GlobalCodes  set Code='SelfPay',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=5, ExternalCode1='H01', ExternalCode2='' Where Category='VaccineFunding' and CodeName='Self pay' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='Some or all vaccine costs covered' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','Some or all vaccine costs covered','AllVaccineCostsCovered',NULL,'Y','Y',6,'IS00','') END ELSE BEGIN UPDATE GlobalCodes  set Code='AllVaccineCostsCovered',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=6, ExternalCode1='IS00', ExternalCode2='' Where Category='VaccineFunding' and CodeName='Some or all vaccine costs covered' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='Third party or private insurance' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','Third party or private insurance','PrivateInsuranc',NULL,'Y','Y',7,'H03','') END ELSE BEGIN UPDATE GlobalCodes  set Code='PrivateInsuranc',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=7, ExternalCode1='H03', ExternalCode2='' Where Category='VaccineFunding' and CodeName='Third party or private insurance' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='Underinsured (no vaccine costs covered and not FQC/RHC)' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','Underinsured (no vaccine costs covered and not FQC/RHC)','Underinsured',NULL,'Y','Y',8,'IS01','') END ELSE BEGIN UPDATE GlobalCodes  set Code='Underinsured',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=8, ExternalCode1='IS01', ExternalCode2='' Where Category='VaccineFunding' and CodeName='Underinsured (no vaccine costs covered and not FQC/RHC)' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligibility not determined/unknown' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligibility not determined/unknown','VFCNotDetermined',NULL,'Y','Y',9,'VOO','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFCNotDetermined',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=9, ExternalCode1='VOO', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligibility not determined/unknown' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC Eligible' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('VaccineFunding','VFC Eligible','VFC Eligible',NULL,'Y','Y',10,'V04') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFC Eligible',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=10, ExternalCode1='V04' Where Category='VaccineFunding' and CodeName='VFC Eligible' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible - Local-specific eligibility' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible - Local-specific eligibility','VFCEligibleLocalEligibility',NULL,'Y','Y',11,'V07','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFCEligibleLocalEligibility',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=11, ExternalCode1='V07', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible - Local-specific eligibility' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible - Medicaid/Medicaid Managed Care' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible - Medicaid/Medicaid Managed Care','VFCEligibleMedicaidCare',NULL,'Y','Y',12,'V02','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFCEligibleMedicaidCare',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=12, ExternalCode1='V02', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible - Medicaid/Medicaid Managed Care' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible - State-specific eligibility (e.g., S-CHIP plan)' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible - State-specific eligibility (e.g., S-CHIP plan)','VFCEligibleStateSpecific',NULL,'Y','Y',13,'V06','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFCEligibleStateSpecific',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=13, ExternalCode1='V06', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible - State-specific eligibility (e.g., S-CHIP plan)' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible – American Indian/Alaskan Native' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible – American Indian/Alaskan Native','VFCEligibleAmericanNative',NULL,'Y','Y',14,'V04','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFCEligibleAmericanNative',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=14, ExternalCode1='V04', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible – American Indian/Alaskan Native' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible – Federally Qualified Health Center Patient (under-insured)' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible – Federally Qualified Health Center Patient (under-insured)','VFC eligible under-insured',NULL,'Y','Y',15,'V05','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFC eligible under-insured',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=15, ExternalCode1='V05', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible – Federally Qualified Health Center Patient (under-insured)' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC eligible – Uninsured' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('VaccineFunding','VFC eligible – Uninsured','VFC eligibleUninsured',NULL,'Y','Y',16,'V03','') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFC eligibleUninsured',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=16, ExternalCode1='V03', ExternalCode2='' Where Category='VaccineFunding' and CodeName='VFC eligible – Uninsured' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'VaccineFunding' and CodeName='VFC Not Eligible' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('VaccineFunding','VFC Not Eligible','VFC Not Eligible',NULL,'Y','Y',17,'V01') END ELSE BEGIN UPDATE GlobalCodes  set Code='VFC Not Eligible',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=17, ExternalCode1='V01' Where Category='VaccineFunding' and CodeName='VFC Not Eligible' END 


