 --DFA scripts for DAST document.
/******************************************************************************** 

-- *****History****  
/*       Date           Author				Description                   */
/*       17/APR/2018	Chethan N			Westbridge-Customizations task #4650                   */
*********************************************************************************/
 
 DECLARE @FormNames VARCHAR(MAX) = 'CoreDast'  
 
DECLARE @FormCollectionId INT
  
 UPDATE DocumentCodes   SET FormCollectionId = NULL   
 WHERE DocumentCodeId = 1651
 
 
 DELETE FROM FormItems   
 WHERE FormSectionId IN (SELECT FormSectionId FROM FormSections   WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,','))))    
 
 DELETE FROM FormSectionGroups   WHERE FormSectionId IN (SELECT FormSectionId FROM FormSections   WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,','))))    
 
 DELETE FROM FormSections   WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,',')))    
 
 DECLARE @FormCollectionIds VARCHAR(MAX)    
 Select @FormCollectionIds = STUFF( (SELECT ',' + CAST(F1.FormCollectionId AS VARCHAR(MAX))      FROM FormCollectionForms F1      
 Where F1.FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,',')))      FOR XML PATH('') ), 1,1,'')       FROM Forms F    WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,',')))      
 
 DELETE FROM FormCollectionForms  WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,',')))    
 
 DELETE FROM FormCollections  WHERE FormCollectionId IN (SELECT Token FROM [dbo].[SplitString] (@FormCollectionIds,','))    
 
 DELETE FROM Forms   
 WHERE FormId IN (SELECT FormId FROM Forms WHERE FormName IN( SELECT Token FROM [dbo].[SplitString] (@FormNames,',')))
 
 DECLARE @FormId51324 INT INSERT INTO Forms(FormName, TableName, TotalNumberOfColumns, Active, RetrieveStoredProcedure, JavascriptFilePath) values('CoreDast','DocumentDASTs',2,'Y','ssp_GetDocumentDasts','Modules/DAST/Scripts/Dast.js') SET @FormId51324 = SCOPE_IDENTITY()    
 
 DECLARE @FormCollectionId51324 INT    
 INSERT INTO dbo.FormCollections (NumberOfForms)      VALUES (1)
 SET @FormCollectionId51324 = SCOPE_IDENTITY()    
 
 INSERT INTO FormCollectionForms (FormCollectionId, FormId, Active, FormOrder)      
 VALUES (@FormCollectionId51324, @FormId51324, 'Y', 1);
 
 DECLARE @FormSectionId60373 INT INSERT INTO dbo.FormSections(formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(@FormId51324,1,NULL,'DAST','Y',NULL,NULL,NULL,2) SET @FormSectionId60373 = SCOPE_IDENTITY()
 
 DECLARE @FormSectionGroupId61039 INT INSERT INTO dbo.FormSectionGroups (formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(@FormSectionId60373,1,NULL,'Y',NULL,NULL,NULL,2) SET @FormSectionGroupId61039 = SCOPE_IDENTITY()
DECLARE @FormSectionGroupId61040 INT INSERT INTO dbo.FormSectionGroups (formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(@FormSectionId60373,2,NULL,'Y',NULL,NULL,NULL,1) SET @FormSectionGroupId61040 = SCOPE_IDENTITY()

INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','1. Have you used drugs other than those required for medical reasons?',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',2,'Y','RADIOYN','MedicalReason','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','2. Have you abused prescription drugs?',3,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',4,'Y','RADIOYN','PrescriptionDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','3. Do you abuse more than one drug at a time?',5,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',6,'Y','RADIOYN','OneDrugAtATime','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','4. Can you get through the week without using drugs? (other than those required for a medical reason)',7,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',8,'Y','RADIOYN','WeekWithoutDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','5. Are you always able to stop using drugs when you want to?',9,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',10,'Y','RADIOYN','StopDrug','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','6. Do you abuse drugs on a continuous basis?',11,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',12,'Y','RADIOYN','ContinuousDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','7. Do you try to limit your drug use to certain situations?',13,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',14,'Y','RADIOYN','LimitDrugsSituations','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','8. Have you had “blackouts” or “flashbacks” as a result of drug use?',15,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',16,'Y','RADIOYN','Flashback','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','9. Do you ever feel bad about your drug abuse?',17,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',18,'Y','RADIOYN','DrugAbuse','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','10. Does your spouse (or parents) ever complain about your involvement with drugs?',19,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',20,'Y','RADIOYN','InvolvementWithDrug','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','11. Do your friends or relatives know or suspect you abuse drugs?',21,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',22,'Y','RADIOYN','SuspectDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','12. Has drug abuse ever created problems between you and your spouse?',23,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',24,'Y','RADIOYN','ProblemCreatedSpouse','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','13. Has any family member ever sought help for problems related to your drug use?',25,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',26,'Y','RADIOYN','ShoughtHelp','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','14. Have you ever lost friends because of your use of drugs?',27,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',28,'Y','RADIOYN','LostFriends','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','15. Have you ever neglected your family or missed work because of your use of drugs?',29,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',30,'Y','RADIOYN','NeglectedDrug','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','16. Have you ever been in trouble at work because of drug abuse?',31,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',32,'Y','RADIOYN','TroubleWork','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','17. Have you ever lost a job because of drug abuse?',33,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',34,'Y','RADIOYN','LostJob','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','18. Have you gotten into fights when under the influence of drugs?',35,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',36,'Y','RADIOYN','GottenIntoFights','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','19. Have you ever been arrested because of unusual behavior while under the influence of drugs?',37,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',38,'Y','RADIOYN','ArrestedDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','20. Have you ever been arrested for driving while under the influence of drugs?',39,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',40,'Y','RADIOYN','ArrestedDrivingDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','21. Have you engaged in illegal activities in order to obtain drugs?',41,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',42,'Y','RADIOYN','ObtainDrug','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','22. Have you ever been arrested for possession of illegal drugs?',43,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',44,'Y','RADIOYN','PossessionIligalDrugs','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','23. Have you ever experienced withdrawal symptoms as a result of heavy drug intake?',45,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',46,'Y','RADIOYN','HeavyDrugIntake','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','24. Have you had medical problems as a result of your drug use (e.g. memory loss, hepatitis, convulsions, bleeding, etc.)?',47,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',48,'Y','RADIOYN','MedicalProblem','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','25. Have you ever gone to anyone for help for a drug problem?',49,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',50,'Y','RADIOYN','GoneAnyoneHelp','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','26. Have you ever been in a hospital for medical problems related to your drug use?',51,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',52,'Y','RADIOYN','HospitalisedDrug','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','27. Have you ever been involved in a treatment program specifically related to drug use?',53,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',54,'Y','RADIOYN','TreatmentProgram','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5374','28. Have you been treated as an outpatient for problems related to drug abuse?',55,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61039,'5365','',56,'Y','RADIOYN','TreatedAsOutpatient','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61040,'5361','<span id="span_TotalScore" class="form_label" style="padding-left:530px; padding-right: 5px"><b>Total Score</b></span>',57,'Y',NULL,'Score','N',NULL,70,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61040,'5374','<span id="span_Substance" style="padding-left:530px">Score > 11 - no substance abuse problem</span>',58,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO Formitems (formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(@FormSectionId60373,@FormSectionGroupId61040,'5374','<span id="span_Substance" style="padding-left:530px">Score 12 or more - substance abuse problem</span> ',59,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

SELECT @FormCollectionId = FormCollectionId from FormCollectionForms FCF
JOIN Forms F ON F.FormId = FCF.FormId
WHERE F.FormName = 'CoreDast'
AND ISNULL(F.RecordDeleted, 'N') = 'N' 
AND ISNULL(FCF.RecordDeleted, 'N') = 'N'

 UPDATE DocumentCodes   SET FormCollectionId = @FormCollectionId   
 WHERE DocumentCodeId = 1651