IF NOT EXISTS (SELECT * FROM dbo.GlobalCodeCategories WHERE Category = 'ImmunizationRoute') 
BEGIN 
	INSERT INTO dbo.GlobalCodeCategories ( Category, CategoryName, Active, AllowAddDelete, AllowCodeNameEdit, AllowSortOrderEdit, Description, UserDefinedCategory, HasSubcodes, UsedInPracticeManagement, UsedInCareManagement) 
	VALUES('ImmunizationRoute','Immunization Route','Y','Y','N','N',NULL,'N','N','N','Y') 
END

IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationRoute' and CodeName='Intramuscular' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('ImmunizationRoute','Intramuscular','Intramuscular',NULL,'Y','N',1,'C28161') END ELSE BEGIN UPDATE GlobalCodes  set Code='Intramuscular',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=1, ExternalCode1='C28161' Where Category='ImmunizationRoute' and CodeName='Intramuscular' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationRoute' and CodeName='Oral' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationRoute','Oral','Oral',NULL,'Y','Y',2,'C38288','NCIT') END ELSE BEGIN UPDATE GlobalCodes  set Code='Oral',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=2, ExternalCode1='C38288', ExternalCode2='NCIT' Where Category='ImmunizationRoute' and CodeName='Oral' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationRoute' and CodeName='Subcutaneous' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1,ExternalCode2) values('ImmunizationRoute','Subcutaneous','Subcutaneous',NULL,'Y','Y',3,'C38299','NCIT') END ELSE BEGIN UPDATE GlobalCodes  set Code='Subcutaneous',Description=NULL,Active='Y',CannotModifyNameOrDelete='Y',SortOrder=3, ExternalCode1='C38299', ExternalCode2='NCIT' Where Category='ImmunizationRoute' and CodeName='Subcutaneous' END 
IF NOT EXISTS (SELECT * FROM dbo.GlobalCodes WHERE Category = 'ImmunizationRoute' and CodeName='Unknown' ) BEGIN INSERT INTO GlobalCodes (Category, CodeName, Code, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('ImmunizationRoute','Unknown','Unknown',NULL,'Y','N',4,'C28161') END ELSE BEGIN UPDATE GlobalCodes  set Code='Unknown',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=4, ExternalCode1='C28161', ExternalCode2=NULL Where Category='ImmunizationRoute' and CodeName='Unknown' END 

