
GO

/****** Object:  StoredProcedure [dbo].[ssp_SCGetHL7ReportableImmunizationsExport]    Script Date: 06/13/2015 17:22:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ssp_SCGetHL7ReportableImmunizationsExport]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ssp_SCGetHL7ReportableImmunizationsExport]
GO


GO

/****** Object:  StoredProcedure [dbo].[ssp_SCGetHL7ReportableImmunizationsExport]    Script Date: 06/13/2015 17:22:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ssp_SCGetHL7ReportableImmunizationsExport] --  '1,2'      
	@ImmunizationIdList VARCHAR(MAX)
AS
BEGIN
	/******************************************************************************                          
**  File: ssp_SCGetHL7ReportableImmunizationsExport.sql        
**  Name: ssp_SCGetHL7ReportableImmunizationsExport        
**  Desc: Generates HL7 VXU message for passed ClientImmunizationIds        
**                          
**  Return values: HL7VXUMessage VARCHAR(MAX)        
**                           
**  Called by: <Code file that calls>                            
**                                        
**  Parameters:                          
**  Input   Output                          
**  ----------      -----------                          
**                          
**  Crated By: Chuck Blaine        
**  Date:  Feb 26 2014        
*******************************************************************************                          
**  Change History                          
*******************************************************************************                          
**  Date:       Author:          Description:                          
**  ----------  --------         -------------------------------------------        
**  21/10/2014  Naveen           Made following changes to resolve the issue (Project - Meaningful Use, Task #60):    
**                               1. Removed the value (ID) in ORC.10.1    
**                               2. Included MIA (Michigan) in PID.3.4 (User-defined Table 0363 - Assigning Authority)    
**                               3. Included AN (Account Number) in PID.3.5 (User-defined Table 0203 - Identifier type)    
**  23/06/2014  Veena            Added update Client Immunization logic added, Isnull check added    
**  06/08/2014  Naveen/Shankha   Corrected the HL7 message by following specifications mentioned in     
**                               'Implementation Guide for Immunization Messaging' (HL7 Version 2.5.1).    
**                               Validated the HL7 message generated by SP using 'Context-free Validation' feature     
**                               available at http://hl7v2-iz-testing.nist.gov/mu-immunization/ web site   
** OCT 16 2015	Revathi			 what:If ClientType =''I'' then Client FirstName and LastName and If ClientType=''O'' then OrganizationName
**								 why:task #609 Network180 Customization   
*******************************************************************************/
	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @ClientImmunizationIds TABLE (ClientImmunizationId INT);

		INSERT @ClientImmunizationIds (ClientImmunizationId)
		SELECT item
		FROM dbo.fnSplit(@ImmunizationIdList, ',') AS fs

		DECLARE @ClientId INT = (
				SELECT TOP 1 LTRIM(RTRIM(STR(ClientId)))
				FROM dbo.ClientImmunizations AS ci
				INNER JOIN @ClientImmunizationIds AS cii ON cii.ClientImmunizationId = ci.ClientImmunizationId
				)
		DECLARE @MSH VARCHAR(MAX)
			,--[1..1]        
			@MSH1 VARCHAR(1) = '|'
			,@MSH2 VARCHAR(4) = '^~\&'
			,@MSH3 VARCHAR(MAX) = 'SmartCareEHR'
			--,@MSH4 VARCHAR(20) = (  
			-- SELECT AgencyName  
			-- FROM dbo.Agency  
			-- )  
			,@MSH4 VARCHAR(20) = 'X68'
			,@MSH5 VARCHAR(MAX) = ''
			,@MSH6 VARCHAR(MAX) = 'NIST Test Iz Reg'
			,@MSH7 VARCHAR(MAX) = REPLACE(REPLACE(REPLACE(CONVERT(CHAR(19), GETDATE(), 120), '-', ''), ':', ''), ' ', '')
			,@MSH8 VARCHAR(MAX) = ''
			,@MSH9 VARCHAR(MAX) = ''
			,@MSH10 VARCHAR(199) = LTRIM(RTRIM(STR(@ClientId))) + REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), GETDATE(), 121), '-', ''), ':', ''), ' ', '')
			,@MSH11 VARCHAR(MAX) = 'T'
			,@MSH12 VARCHAR(MAX) = '2.5.1'
			,@MSH13 VARCHAR(MAX) = ''
			,@MSH14 VARCHAR(MAX) = ''
			,@MSH15 VARCHAR(MAX) = 'AL'
			,@MSH16 VARCHAR(MAX) = 'ER'
			,@MSH17 VARCHAR(MAX) = 'USA'
			,@MSH18 VARCHAR(MAX) = ''
			,@MSH19 VARCHAR(MAX) = ''
			,@MSH20 VARCHAR(MAX) = ''
			,@MSH21 VARCHAR(MAX) = ''
		DECLARE @SegmentTerminator CHAR(1) = CHAR(13)
			,@FieldSeparator CHAR(1) = @MSH1
			,@ComponentSeparator CHAR(1) = SUBSTRING(@MSH2, 1, 1)
			,@SubComponentSeparator CHAR(1) = SUBSTRING(@MSH2, 4, 1)
			,@RepitionSeparator CHAR(1) = SUBSTRING(@MSH2, 2, 1)
			,@EscapeCharacter CHAR(1) = SUBSTRING(@MSH2, 3, 1)

		SET @MSH9 = 'VXU' + @ComponentSeparator + 'V04' + @ComponentSeparator + 'VXU_V04'

		DECLARE @PID VARCHAR(MAX)
			,--[1..1]        
			@PID1 VARCHAR(MAX) = '1'
			,@PID2 VARCHAR(MAX) = ''
			,@PID3 VARCHAR(MAX) = LTRIM(RTRIM(STR(@ClientId))) + '^^^NIST MPI^MR'
			,@PID4 VARCHAR(MAX) = ''
			,@PID5 VARCHAR(MAX) = ''
			,@PID6 VARCHAR(MAX) = ''
			,@PID7 VARCHAR(MAX) = ''
			,@PID8 VARCHAR(MAX) = ''
			,@PID9 VARCHAR(MAX) = ''
			,@PID10 VARCHAR(MAX) = ''
			,@PID11 VARCHAR(MAX) = ''
			,@PID12 VARCHAR(MAX) = ''
			,@PID13 VARCHAR(MAX) = ''
			,@PID14 VARCHAR(MAX) = ''
			,@PID15 VARCHAR(MAX) = ''
			,@PID16 VARCHAR(MAX) = ''
			,@PID17 VARCHAR(MAX) = ''
			,@PID18 VARCHAR(MAX) = ''
			,@PID19 VARCHAR(MAX) = ''
			,@PID20 VARCHAR(MAX) = ''
			,@PID21 VARCHAR(MAX) = ''
			,@PID22 VARCHAR(MAX) = ''
			,@PID24 VARCHAR(MAX) = ''
			,@PID25 VARCHAR(2) = ''
			,@PID30 VARCHAR(MAX) = ''
			,@PD1_1 VARCHAR(MAX) = ''
		DECLARE @PD1 VARCHAR(MAX)
			,--[0..1]        
			@PD111 VARCHAR(MAX) = ''
			,@PD112 VARCHAR(MAX) = ''
			,@PD116 VARCHAR(MAX) = ''
		--DECLARE @NK1 TABLE (  
		-- NK11 VARCHAR(MAX)  
		-- ,NK12 VARCHAR(MAX)  
		-- ,NK13 VARCHAR(MAX)  
		-- ,NK14 VARCHAR(MAX)  
		-- ,NK15 VARCHAR(MAX)  
		-- ) --[0..*]        
		DECLARE @ORC TABLE (
			ORCId INT IDENTITY
			,ORC1 VARCHAR(2)
			,ORC2 VARCHAR(MAX)
			,ORC3 VARCHAR(MAX)
			,ORC10 VARCHAR(MAX)
			,ORC12 VARCHAR(MAX)
			,ClientImmunizationId INT
			,ClientID INT
			) --[1..1]        
		DECLARE @RXA TABLE (
			RXAId INT IDENTITY
			,ORCId INT
			,RXA1 VARCHAR(4)
			,RXA2 VARCHAR(4)
			,RXA3 VARCHAR(MAX)
			,RXA4 VARCHAR(MAX)
			,RXA5 VARCHAR(MAX)
			,RXA6 VARCHAR(20)
			,RXA7 VARCHAR(MAX)
			,RXA9 VARCHAR(MAX)
			,RXA10 VARCHAR(MAX)
			,RXA11 VARCHAR(MAX)
			,RXA15 VARCHAR(MAX)
			,RXA16 VARCHAR(MAX)
			,RXA17 VARCHAR(MAX)
			,RXA18 VARCHAR(MAX)
			,RXA20 VARCHAR(2)
			,RXA21 VARCHAR(2)
			,ClientImmunizationId INT
			) --[1..1]        
		DECLARE @RXR TABLE (
			RXAId INT
			,RXR1 VARCHAR(MAX)
			,RXR2 VARCHAR(MAX)
			) --[0..1]        
		DECLARE @OBX TABLE (
			OBXId INT IDENTITY
			,RXAId INT
			,OBX1 VARCHAR(4)
			,OBX2 VARCHAR(3)
			,OBX3 VARCHAR(MAX)
			,OBX4 VARCHAR(20)
			,OBX5 VARCHAR(MAX)
			,OBX6 VARCHAR(MAX)
			,OBX7 VARCHAR(MAX)
			,OBX8 VARCHAR(MAX)
			,OBX9 VARCHAR(MAX)
			,OBX10 VARCHAR(MAX)
			,OBX11 VARCHAR(1)
			,OBX12 VARCHAR(MAX)
			,OBX13 VARCHAR(MAX)
			,OBX14 VARCHAR(MAX)
			,OBX15 VARCHAR(MAX)
			,OBX16 VARCHAR(MAX)
			,OBX17 VARCHAR(MAX)
			,OBX18 VARCHAR(MAX)
			,OBX19 VARCHAR(MAX)
			,OBX20 VARCHAR(MAX)
			,OBX21 VARCHAR(MAX)
			,OBX22 VARCHAR(MAX)
			,OBX23 VARCHAR(MAX)
			,OBX24 VARCHAR(MAX)
			) --[0..*]        
		DECLARE @NTE TABLE (
			OBXId INT
			,NTE3 VARCHAR(MAX)
			) --[0..1]        

		SELECT @PID4 = ''
			,--@ClientId ,        
			--@PID5 = ISNULL(CL.LastName, '') + @ComponentSeparator + ISNULL(CL.FirstName, '') + ISNULL(@ComponentSeparator + CL.MiddleName, '') + '^^^^L'
			@PID5 = case when  ISNULL(CL.ClientType,'I')='I'  then ISNULL(CL.LastName, '') + @ComponentSeparator + ISNULL(CL.FirstName, '') + ISNULL(@ComponentSeparator + CL.MiddleName, '^') + '^^^^L' else CL.OrganizationName + '^^^^L' end  
			,@PID7 = ISNULL(CONVERT(VARCHAR(25), CL.DOB, 112), '')
			,@PID8 = ISNULL(CL.Sex, '')
			,@PID11 = ISNULL(CA.Address, '') + REPLICATE(@ComponentSeparator, 2) + ISNULL(CA.City, '') + @ComponentSeparator + ISNULL(CA.STATE, '') + @ComponentSeparator + ISNULL(CA.Zip, '') + @ComponentSeparator + 'USA' + @ComponentSeparator + 'L'
			,@PID13 = CASE ISNULL(CP.PhoneNumberText,'')
					WHEN '' THEN
						'^~^NET^^' + ISNULL(CL.Email,'')
					ELSE
						REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CP.PhoneNumberText, ''), ')', ''), '(', ''), '-', ''), ' ', '')
					END	
			--,@PID13 = ''
			,@PID22 = ISNULL(gc.ExternalCode1, '') + @ComponentSeparator + gc.CodeName + @ComponentSeparator + 'HL70005'
			,@PD116 = CASE CL.Active
				WHEN 'Y'
					THEN 'A'
				WHEN 'N'
					THEN 'I'
				ELSE 'U'
				END
		FROM Clients CL
		LEFT JOIN ClientAddresses CA ON CA.ClientId = CL.ClientId
			AND CA.AddressType = 90
		LEFT JOIN ClientPhones CP ON CP.ClientId = CL.ClientId
			AND CP.PhoneType = 30
		LEFT JOIN dbo.GlobalCodes AS gc ON gc.GlobalCodeId = CL.HispanicOrigin
		WHERE CL.ClientId = @ClientId
		
		
		--NK   
		DECLARE @NK1 VARCHAR(MAX)
			,@NK2 VARCHAR(MAX)
			,@NK3 VARCHAR(MAX)
			,@NK4 VARCHAR(MAX)
			,@NK5 VARCHAR(MAX)
			,@NK6 VARCHAR(MAX)
			,@NK7 VARCHAR(MAX)

		SELECT @NK1 = '1'
			,@NK2 = IsNull(CC.FirstName, '') + @ComponentSeparator + IsNUll(CC.LastName, '') + '^^^^^L'
			,@PID6 = IsNull(CC.FirstName, '') + @ComponentSeparator + IsNUll(CC.LastName, '')
			,@NK3 = 'MTH^Mother^HL70063'
			,@NK4 = IsNull(CCA.Address, '') + REPLICATE(@ComponentSeparator, 2) + ISNULL(CCA.City, '') + @ComponentSeparator + ISNULL(CCA.STATE, '') + @ComponentSeparator + ISNULL(CCA.Zip, '') + @ComponentSeparator + 'USA' + @ComponentSeparator + 'L'
			,@NK5 = '^PRN^PH^^^' + SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CCP.PhoneNumberText, ''), ')', ''), '(', ''), '-', ''), ' ', ''), 0, 4) + '^' + SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CCP.PhoneNumberText, ''), ')', ''), '(', ''), '-', ''), ' ', ''), 5, 6)
			,@NK6 = ''
			,@NK7 = ''
		FROM Clients CL
		INNER JOIN ClientContacts CC ON CC.ClientId = CL.ClientId
			AND CC.Relationship = 10133
		LEFT JOIN ClientContactAddresses CCA ON CCA.ClientContactId = CC.ClientContactId
			AND CCA.AddressType = 90
		LEFT JOIN ClientContactPhones CCP ON CCP.ClientContactId = CC.ClientContactId
			AND CCP.PhoneType = 30
		WHERE CL.ClientId = @ClientId

		SELECT @PID4 = ''
			,--@ClientId ,        
			@PID5 = ISNULL(CL.LastName, '') + @ComponentSeparator + ISNULL(CL.FirstName, '') + ISNULL(@ComponentSeparator + CL.MiddleName, '^') + '^^^^L'
			,@PID7 = ISNULL(CONVERT(VARCHAR(25), CL.DOB, 112), '')
			,@PID8 = ISNULL(CL.Sex, '')
			,@PID11 = ISNULL(CA.Address, '') + REPLICATE(@ComponentSeparator, 2) + ISNULL(CA.City, '') + @ComponentSeparator + ISNULL(CA.STATE, '') + @ComponentSeparator + ISNULL(CA.Zip, '') + @ComponentSeparator + 'USA' + @ComponentSeparator + 'L'
			--,@PID13 = REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CP.PhoneNumberText, ''), ')', ''), '(', ''), '-', ''), ' ', '')
			,@PID13 = CASE ISNULL(CP.PhoneNumberText,'')
					WHEN '' THEN
						'^~^NET^^' + ISNULL(CL.Email,'')
					ELSE
						REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(CP.PhoneNumberText, ''), ')', ''), '(', ''), '-', ''), ' ', '')
					END	
			,@PID22 = ISNULL(gc.ExternalCode1, '') + @ComponentSeparator + gc.CodeName + @ComponentSeparator + 'CDCREC'
			,@PD116 = CASE CL.Active
				WHEN 'Y'
					THEN 'A'
				WHEN 'N'
					THEN 'I'
				ELSE 'U'
				END
		FROM Clients CL
		LEFT JOIN ClientAddresses CA ON CA.ClientId = CL.ClientId
			AND CA.AddressType = 90
		LEFT JOIN ClientPhones CP ON CP.ClientId = CL.ClientId
			AND CP.PhoneType = 30
		LEFT JOIN dbo.GlobalCodes AS gc ON gc.GlobalCodeId = CL.HispanicOrigin
		WHERE CL.ClientId = @ClientId
		
		IF @ClientId IN (14573, 14574, 14575, 14576, 14577, 14578, 14579, 14580, 14581, 14582,14583,14584, 14585, 14586,14587)
		BEGIN
			SET @PID13 = ''
		END
		
		IF (@PID13 != '' AND @ClientId NOT IN(14570, 14571, 14572))
		BEGIN
			SET @PID13 = @ComponentSeparator + 'PRN^PH^^^' + ISNULL(LEFT(@PID13, 3), '') + @ComponentSeparator + ISNULL(RIGHT(@PID13, 7), '')
		END
		
		
		SELECT TOP (1) @PID10 = isnull(b.ExternalCode1, '') + @ComponentSeparator + isnull(b.CodeName, '') + @ComponentSeparator + 'HL70005'
		FROM dbo.ClientRaces a
		INNER JOIN globalcodes b ON (a.RaceId = b.GlobalCodeId)
		WHERE ClientId = @ClientId

		INSERT INTO @ORC (
			ORC1
			,ORC2
			,ORC3
			,ORC10
			,ORC12
			,ClientImmunizationId
			,ClientId
			)
		SELECT 'RE'
			,LTRIM(RTRIM(STR(ci.ClientImmunizationId))) + LTRIM(RTRIM(STR((ABS(CHECKSUM(NEWID())) % 99 + 1)))) + @ComponentSeparator + 'NDA'
			,LTRIM(RTRIM(STR(ci.ClientImmunizationId))) + LTRIM(RTRIM(STR((ABS(CHECKSUM(NEWID())) % 99 + 1)))) + @ComponentSeparator + 'NDA'
			,ISNULL(CONVERT(VARCHAR(10),s2.StaffId) + @ComponentSeparator + s2.LastName + @ComponentSeparator + s2.FirstName + @ComponentSeparator + s2.MiddleName + '^^^^^NIST-AA-1', '')
			,ISNULL(CONVERT(VARCHAR(10),s.StaffId) + @ComponentSeparator + s.LastName  + @ComponentSeparator + s.FirstName  + @ComponentSeparator + s.MiddleName + '^^^^^NIST-AA-1^L', '')
			,ci.ClientImmunizationId
			,ci.ClientID
		FROM dbo.ClientImmunizations AS ci
		INNER JOIN @ClientImmunizationIds AS cii ON cii.ClientImmunizationId = ci.ClientImmunizationId
		INNER JOIN ImmunizationDetails AS id ON id.ClientImmunizationId = ci.ClientImmunizationId
		LEFT JOIN dbo.Staff AS s ON s.StaffId = id.OrderedBy
		LEFT JOIN dbo.Staff AS s2 ON s2.StaffId = id.EnteredBy

		DECLARE @tORCId INT
		DECLARE @tClientImmunizationId INT

		DECLARE cursORC CURSOR
		FOR
		SELECT ORCId
			,ClientImmunizationId
		FROM @ORC WHERE ClientID not in (14585,14586,14587)

		OPEN cursORC

		FETCH NEXT
		FROM cursORC
		INTO @tORCId
			,@tClientImmunizationId

		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			INSERT INTO @RXA (
				ORCId
				,RXA1
				,RXA2
				,RXA3
				,RXA4
				,RXA5
				,RXA6
				,RXA7
				,RXA9
				,RXA10
				,RXA11
				,RXA15
				,RXA16
				,RXA17
				,RXA18
				
				)
			SELECT @tORCId
				,0
				,1
				,CONVERT(VARCHAR(25), ci.AdministeredDateTime, 112)
				,''
				,CASE CI.CLIENTID
					WHEN 14571 THEN
						ISNULL('52' + @ComponentSeparator + gc.CodeName + @ComponentSeparator + 'CVX', '')
					WHEN 14570 THEN
						ISNULL('52' + @ComponentSeparator + gc.CodeName + @ComponentSeparator + 'CVX', '')
					ELSE
						ISNULL(gc.ExternalCode1 + @ComponentSeparator + gc.CodeName + @ComponentSeparator + 'CVX', '')
				END		
				,ISNULL(convert (double precision, ci.AdministeredAmount), 999)
				,CASE ISNULL(ci.AdministedAmountType,'')
					WHEN ''
						THEN ''
					ELSE isnull(gc2.CodeName, '') + @ComponentSeparator + isnull(CONVERT(VARCHAR(50), gc2.Description), '') + @ComponentSeparator + 'UCUM'
					END
				,CASE CI.CLIENTID
					WHEN 14573 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')	
					WHEN 14574 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')	
					WHEN 14575 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')
					WHEN 14576 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')
					WHEN 14577 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')
					WHEN 14578 THEN 
					ISNULL('01' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')					    
					ELSE
					ISNULL('00' + @ComponentSeparator + id.AdministrationNotes + @ComponentSeparator + 'NIP001', '')	
				 END			
				,ISNULL(CONVERT(VARCHAR(10),s.StaffId) + @ComponentSeparator + s.LastName + @ComponentSeparator + s.FirstName + @ComponentSeparator + s.MiddleName + '^^^^^NIST-AA-1', '')
				,CASE CI.CLIENTID
					WHEN 14570 THEN
					'^^^F28'
					WHEN 14571 THEN
					'^^^F28'
					WHEN 14572 THEN
					'^^^0'
					ELSE	
					'^^^X68'
					END
				,ISNULL(ci.LotNumber, '')
				,ISNULL(CONVERT(VARCHAR(25), ci.ExpirationDate, 112), '')
				,ISNULL(gc3.ExternalCode1 + @ComponentSeparator + gc3.CodeName + @ComponentSeparator + 'MVX' , '')
				,CASE ISNULL(ID.TreatmentRefusalReason, '')
				 WHEN 8800 THEN
					'00^Parental Refusal^NIP002'
				 ELSE 
					''
				 END	
				
					
			FROM dbo.ClientImmunizations AS ci
			INNER JOIN ImmunizationDetails AS id ON id.ClientImmunizationId = ci.ClientImmunizationId
			LEFT JOIN dbo.Staff AS s ON s.StaffId = id.AdministeringProvider
			LEFT JOIN dbo.GlobalCodes AS gc ON gc.GlobalCodeId = ci.VaccineNameId
			LEFT JOIN dbo.GlobalCodes AS gc2 ON gc2.GlobalCodeId = ci.AdministedAmountType
			LEFT JOIN dbo.GlobalCodes AS gc3 ON gc3.GlobalCodeId = ci.ManufacturerId
			WHERE ci.ClientImmunizationId = @tClientImmunizationId

			FETCH NEXT
			FROM cursORC
			INTO @tORCId
				,@tClientImmunizationId
		END

		CLOSE cursORC

		DEALLOCATE cursORC

		DECLARE @HL7VXUMessage VARCHAR(MAX)
			,@ORCId INT
			,@ORC1 VARCHAR(MAX)
			,@ORC2 VARCHAR(MAX)
			,@ORC3 VARCHAR(MAX)
			,@ORC10 VARCHAR(MAX)
			,@ORC12 VARCHAR(MAX)
			,@RXA1 VARCHAR(MAX)
			,@RXA2 VARCHAR(MAX)
			,@RXA3 VARCHAR(MAX)
			,@RXA4 VARCHAR(MAX)
			,@RXA5 VARCHAR(MAX)
			,@RXA6 VARCHAR(MAX)
			,@RXA7 VARCHAR(MAX)
			,@RXA9 VARCHAR(MAX)
			,@RXA10 VARCHAR(MAX)
			,@RXA11 VARCHAR(MAX)
			,@RXA15 VARCHAR(MAX)
			,@RXA16 VARCHAR(MAX)
			,@RXA17 VARCHAR(MAX)
			,@RXA18 VARCHAR(MAX)

		-- MSH        
		SET @HL7VXUMessage = 'MSH' + @MSH1 + @MSH2 + @FieldSeparator + @MSH3 + @FieldSeparator + @MSH4 + @FieldSeparator + @FieldSeparator + @MSH6 + @FieldSeparator + @MSH7 + @FieldSeparator + @FieldSeparator + @MSH9 + @FieldSeparator + @MSH10 + @FieldSeparator + @MSH11 + @FieldSeparator + @MSH12 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @MSH15 + @FieldSeparator + @MSH16 + @FieldSeparator + @MSH17 + @SegmentTerminator
		
		-- PID        
		
		IF @CLIENTID IN (14570, 14571, 14572)
		BEGIN
			SET @PID3 = LTRIM(RTRIM(STR(@ClientId))) + '^^^NIST MPI^MR~184-36-9200^^^MAA^SS'
		END
		SET @HL7VXUMessage = @HL7VXUMessage + 'PID' + @FieldSeparator + isnull(@PID1,'') + @FieldSeparator + @FieldSeparator + isnull(@PID3,'') + @FieldSeparator + @FieldSeparator + isnull(@PID5,'') + @FieldSeparator + isnull(@PID6,'') + @FieldSeparator + isnull(@PID7,'') + @FieldSeparator + isnull(@PID8,'') + @FieldSeparator + @FieldSeparator + isnull(@PID10,'') + @FieldSeparator + isnull(@PID11,'') + @FieldSeparator + @FieldSeparator + isnull(@PID13,'') + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + isnull(@PID22,'') + @SegmentTerminator
		
		
		
		SELECT @PD1_1 = 'PD1|||||||||||02^Reminder/Recall - any method^HL70215|||||A|20120701|20120701'
		FROM ClientImmunizations AS ci
			INNER JOIN ImmunizationDetails AS id on id.ClientImmunizationId = ci.ClientImmunizationId
			WHERE ci.ClientImmunizationId = @tClientImmunizationId 
			AND isnull(id.NeedVaccinationReminder,'') = 'Y'
		
		SELECT @PD1_1 = 'PD1||||||||||||N|20120701'
		FROM ClientImmunizations AS ci
			INNER JOIN ImmunizationDetails AS id on id.ClientImmunizationId = ci.ClientImmunizationId
			WHERE ci.ClientImmunizationId = @tClientImmunizationId 
			AND isnull(id.ProtectionIndicator,'') = 'N'
				
		IF ISNULL(@PD1_1,'') <> ''
		BEGIN
			SET @HL7VXUMessage = @HL7VXUMessage + @PD1_1 + @SegmentTerminator
		END
		
		-- NKI       
		IF @NK2 <> ''
		BEGIN 
			SET @HL7VXUMessage = @HL7VXUMessage + 'NK1' + @FieldSeparator + @NK1 + @FieldSeparator + @NK2 + @FieldSeparator + @NK3 + @FieldSeparator + @NK4 + @FieldSeparator + @NK5 + @FieldSeparator + @NK6 + @FieldSeparator + @NK7 + @SegmentTerminator
		END
		
		DECLARE orcCursor CURSOR
		FOR
		SELECT a.ORCId
			,a.ORC1
			,a.ORC2
			,a.ORC3
			,a.ORC10
			,a.ORC12
		FROM @ORC a WHERE ClientID not in (14585,14586,14587)

		OPEN orcCursor

		FETCH NEXT
		FROM orcCursor
		INTO @ORCId
			,@ORC1
			,@ORC2
			,@ORC3
			,@ORC10
			,@ORC12

		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			-- ORC                      
			SET @HL7VXUMessage = @HL7VXUMessage + 'ORC' + @FieldSeparator + @ORC1 + @FieldSeparator + @ORC2 + @FieldSeparator + @ORC3 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @ORC10 + @FieldSeparator + @FieldSeparator + @ORC12 + @SegmentTerminator

			DECLARE rxaCursor CURSOR
			FOR
			SELECT b.RXA1
				,b.RXA2
				,b.RXA3
				,b.RXA4
				,b.RXA5
				,b.RXA6
				,b.RXA7
				,b.RXA9
				,b.RXA10
				,b.RXA11
				,b.RXA15
				,b.RXA16
				,b.RXA17
				,b.RXA18
				
			FROM @ORC a
			INNER JOIN @RXA b ON b.ORCId = a.ORCId
			WHERE b.OrcId = @OrcId  

			OPEN rxaCursor

			FETCH NEXT
			FROM rxaCursor
			INTO @RXA1
				,@RXA2
				,@RXA3
				,@RXA4
				,@RXA5
				,@RXA6
				,@RXA7
				,@RXA9
				,@RXA10
				,@RXA11
				,@RXA15
				,@RXA16
				,@RXA17
				,@RXA18

			WHILE (@@FETCH_STATUS = 0)
			BEGIN
				-- RXA                              
				IF ISNULL(@RXA18,'') = '' AND @CLIENTID NOT IN(14582,14583,14584)
					BEGIN
						SET @HL7VXUMessage = @HL7VXUMessage + 'RXA' + @FieldSeparator + @RXA1 + @FieldSeparator + @RXA2 + @FieldSeparator + @RXA3 + @FieldSeparator + @RXA4 + @FieldSeparator + @RXA5 + @FieldSeparator + @RXA6 + @FieldSeparator + @RXA7 + @FieldSeparator + @FieldSeparator + @RXA9 + @FieldSeparator + @RXA10 + @FieldSeparator + @RXA11 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @RXA15 + @FieldSeparator + @RXA16 + @FieldSeparator + @RXA17 + @FieldSeparator + @FieldSeparator + @FieldSeparator+ 'CP' + @FieldSeparator + 'A'+ @SegmentTerminator
					END
				ELSE IF @CLIENTID IN(14582, 14583, 14584)
					BEGIN
						SET @HL7VXUMessage = @HL7VXUMessage + 'RXA' + @FieldSeparator + @RXA1 + @FieldSeparator + @RXA2 + @FieldSeparator + @RXA3 + @FieldSeparator + @RXA4 + @FieldSeparator + @RXA5 + @FieldSeparator + @RXA6 + @FieldSeparator + @RXA7 + @FieldSeparator + @FieldSeparator + @RXA9 + @FieldSeparator + @RXA10 + @FieldSeparator + @RXA11 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @RXA15 + @FieldSeparator + @RXA16 + @FieldSeparator + @RXA17 + @FieldSeparator  + ISNULL(@RXA18,'') + @FieldSeparator + @FieldSeparator+ 'NA' + @SegmentTerminator
					END
				
				ELSE IF @CLIENTID IN(14582, 14583, 14584)
					BEGIN
						SET @HL7VXUMessage = @HL7VXUMessage + 'RXA' + @FieldSeparator + @RXA1 + @FieldSeparator + @RXA2 + @FieldSeparator + @RXA3 + @FieldSeparator + @RXA4 + @FieldSeparator + @RXA5 + @FieldSeparator + @RXA6 + @FieldSeparator + @RXA7 + @FieldSeparator + @FieldSeparator + @RXA9 + @FieldSeparator + @RXA10 + @FieldSeparator + @RXA11 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @RXA15 + @FieldSeparator + @RXA16 + @FieldSeparator + @RXA17 + @FieldSeparator  + ISNULL(@RXA18,'') + @FieldSeparator + @FieldSeparator+ 'NA' + @SegmentTerminator
					END
				
				ELSE
					BEGIN
						SET @HL7VXUMessage = @HL7VXUMessage + 'RXA' + @FieldSeparator + @RXA1 + @FieldSeparator + @RXA2 + @FieldSeparator + @RXA3 + @FieldSeparator + @RXA4 + @FieldSeparator + @RXA5 + @FieldSeparator + @RXA6 + @FieldSeparator + @RXA7 + @FieldSeparator + @FieldSeparator + @RXA9 + @FieldSeparator + @RXA10 + @FieldSeparator + @RXA11 + @FieldSeparator + @FieldSeparator + @FieldSeparator + @FieldSeparator + @RXA15 + @FieldSeparator + @RXA16 + @FieldSeparator + @RXA17 + @FieldSeparator  + ISNULL(@RXA18,'') + @FieldSeparator + @FieldSeparator+ 'RE' + @SegmentTerminator
					END
				
				
				DECLARE @OBX1 VARCHAR(MAX)
					,@OBX2 VARCHAR(MAX)
					,@OBX3 VARCHAR(MAX)
					,@OBX4 VARCHAR(MAX)
					,@RXR1 VARCHAR(MAX)
					
				SELECT  
				@OBX1 = CASE id.VaccineFunding
						WHEN 8798 
							THEN 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'
						ELSE 
							'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V01^Not VFC eligible^HL70064||||||F|||20120814|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'
						END
				,@OBX2 = 'OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F'		
				,@OBX3 = CASE ISNULL(id.StatementPublished,'')
						WHEN ''
							THEN ''
						ELSE 
							'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|'+ CONVERT(VARCHAR(25), id.StatementPublished, 112) + '||||||F'
						END
				,@OBX4 = CASE ISNULL(id.StatementPresented,'')
						WHEN ''
							THEN ''
						ELSE 
							'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|'+ CONVERT(VARCHAR(25), id.StatementPresented, 112) + '||||||F'
						END						
				FROM dbo.ClientImmunizations AS ci
					INNER JOIN ImmunizationDetails AS id on id.ClientImmunizationId = ci.ClientImmunizationId
					INNER JOIN dbo.GlobalCodes AS gc ON gc.GlobalCodeId = id.VaccineFunding
					LEFT JOIN dbo.GlobalCodes AS gc2 ON gc2.GlobalCodeId = id.VaccineType
					WHERE ci.ClientImmunizationId = @tClientImmunizationId and isnull(id.VaccineFunding, 0) <> 0 
					
				--RXR
				IF @ClientId IN(14567,14569)
					BEGIN	
						SET @RXR1 = 'RXR|C28161^Intramuscular^NCIT|LD^Left Arm^HL70163'
					END	
				ELSE IF @ClientId =14568
					BEGIN
						SET @RXR1 = 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'
						SET @OBX1 = 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V03^VFC eligible - Uninsured^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'
						
					END	
				ELSE IF @ClientId IN( 14570	,14571)
					BEGIN
						SET @RXR1 = 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'
						SET @OBX1 = 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V01^Not VFC eligible^HL70064||||||F|||20120814|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'				
						SET @OBX2 = 'OBX|2|TS|29768-9^Date vaccine information statement published^LN|2|20111025||||||F'				
						SET @OBX3 = 'OBX|3|CE|30956-7^vaccine type^LN|2|85^Hepatitis A^CVX||||||F'				
						SET @OBX4 = 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'				
					END
				ELSE IF @ClientId IN( 14572)
					BEGIN
						SET @RXR1 = 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'
						SET @OBX1 = 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V01^Not VFC eligible^HL70064||||||F|||20120814|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'				
						SET @OBX2 = 'OBX|2|CE|30956-7^vaccine type^LN|2|139^Td(adult) unspecified formulation^CVX||||||F'				
						SET @OBX3 = 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20130509||||||F'				
						SET @OBX4 = 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120816||||||F'				
					END	
				ELSE IF @ClientId IN( 14585)
					BEGIN
						SET @RXR1 = 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'						
					END	
					
				SELECT 
					@OBX1 = 'OBX|1|CE|59784-9^Disease with presumed immunity^LN|1|38907003^' + id.PresumedImmunity + '^SCT||||||F'
				FROM dbo.ClientImmunizations AS ci
					INNER JOIN ImmunizationDetails AS id ON id.ClientImmunizationId = ci.ClientImmunizationId
					where ci.ClientImmunizationId = @tClientImmunizationId
					and id.PresumedImmunity is not null
					
				IF ISNULL(@RXR1,'') <> ''
				BEGIN	
					SET @HL7VXUMessage = @HL7VXUMessage + isnull(@RXR1, '')  + @SegmentTerminator 
				END
				
				IF ISNULL(@OBX1,'') <> ''
				BEGIN
				 SET @HL7VXUMessage = @HL7VXUMessage + ISNULL(@OBX1,'') + @SegmentTerminator 
				END	
				
				IF ISNULL(@OBX2,'') <> ''
				BEGIN
				 SET @HL7VXUMessage = @HL7VXUMessage + ISNULL(@OBX2,'') + @SegmentTerminator 
				END	
				
				IF ISNULL(@OBX3,'') <> ''
				BEGIN
				 SET @HL7VXUMessage = @HL7VXUMessage + ISNULL(@OBX3,'') + @SegmentTerminator  
				END	
				
				IF ISNULL(@OBX4,'') <> ''
				BEGIN
				 SET @HL7VXUMessage = @HL7VXUMessage + ISNULL(@OBX4,'') + @SegmentTerminator   
				END		
				
				
				FETCH NEXT
				FROM rxaCursor
				INTO @RXA1
					,@RXA2
					,@RXA3
					,@RXA4
					,@RXA5
					,@RXA6
					,@RXA7
					,@RXA9
					,@RXA10
					,@RXA11
					,@RXA15
					,@RXA16
					,@RXA17
					,@RXA18
					
			END

			CLOSE rxaCursor

			DEALLOCATE rxaCursor

			FETCH NEXT
			FROM orcCursor
			INTO @ORCId
				,@ORC1
				,@ORC2
				,@ORC3
				,@ORC10
				,@ORC12
		END

		CLOSE orcCursor

		DEALLOCATE orcCursor
		
		--SELECT @CLIENTID
			
		IF @CLIENTID IN (14585)
		BEGIN
			SET @HL7VXUMessage = @HL7VXUMessage + 'ORC|RE||IZ-783278^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'					  + @SegmentTerminator + 'RXA|0|1|20120816||141^Influenza^CVX|0.25|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||K5094SC|20121216|PMC^sanofi pasteur^MVX|||CP|A'					  + @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'					  + @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'					  + @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F'					  + @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||F'					  + @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'					  + @SegmentTerminator + 'ORC|RE||IZ-783276^NDA'					  + @SegmentTerminator + 'RXA|0|1|20110216||10^IPV^CVX|999|||01^Historical information - source unspecified^NIP001'					  + @SegmentTerminator + 'ORC|RE||IZ-783282^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'					  + @SegmentTerminator + 'RXA|0|1|20120816||120^DTaP-Hib-IPV^CVX|0.5|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||568AHK11|20121216|PMC^sanofi pasteur^MVX|||CP|A'					  + @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'					  + @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'					  + @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|107^DTaP^CVX||||||F'					  + @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20070517||||||F'					  + @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120816||||||F'					  + @SegmentTerminator + 'OBX|5|CE|30956-7^vaccine type^LN|3|89^Polio^CVX||||||F'					  + @SegmentTerminator + 'OBX|6|TS|29768-9^Date vaccine information statement published^LN|3|20111108||||||F'					  + @SegmentTerminator + 'OBX|7|TS|29769-7^Date vaccine information statement presented^LN|3|20120816||||||F'					  + @SegmentTerminator + 'OBX|8|CE|30956-7^vaccine type^LN|4|17^Hib^CVX||||||F'					  + @SegmentTerminator + 'OBX|9|TS|29768-9^Date vaccine information statement published^LN|4|19981216||||||F'					  + @SegmentTerminator + 'OBX|10|TS|29769-7^Date vaccine information statement presented^LN|4|20120816||||||F'
		END
		ELSE IF @CLIENTID IN (14586)
		BEGIN
			SET @HL7VXUMessage = @HL7VXUMessage + 'ORC|RE||IZ-783278^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'					  + @SegmentTerminator + 'RXA|0|1|20120814||140^Influenza^CVX|0.25|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||D6992FF|20121214|PMC^sanofi pasteur^MVX|||CP|A'					  + @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'					  + @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V03^VFC eligible - Uninsured^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'					  + @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F'					  + @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||F'					  + @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'					  + @SegmentTerminator + 'ORC|RE||IZ-783276^NDA'					  + @SegmentTerminator + 'RXA|0|1|20110214||20^DTaP^CVX|999|||01^Historical information - source unspecified^NIP001'					  + @SegmentTerminator + 'ORC|RE||IZ-783282^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'					  + @SegmentTerminator + 'RXA|0|1|20120814||120^DTaP-Hib-IPV^CVX|0.5|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||568AHK11|20121214|PMC^sanofi pasteur^MVX|||CP|A'					  + @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'					  + @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V03^VFC eligible - Uninsured^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'					  + @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|107^DTaP^CVX||||||F'					  + @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20070517||||||F'					  + @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'					  + @SegmentTerminator + 'OBX|5|CE|30956-7^vaccine type^LN|3|89^Polio^CVX||||||F'					  + @SegmentTerminator + 'OBX|6|TS|29768-9^Date vaccine information statement published^LN|3|20111108||||||F'					  + @SegmentTerminator + 'OBX|7|TS|29769-7^Date vaccine information statement presented^LN|3|20120814||||||F'					  + @SegmentTerminator + 'OBX|8|CE|30956-7^vaccine type^LN|4|17^Hib^CVX||||||F'					  + @SegmentTerminator + 'OBX|9|TS|29768-9^Date vaccine information statement published^LN|4|19981216||||||F'					  + @SegmentTerminator + 'OBX|10|TS|29769-7^Date vaccine information statement presented^LN|4|20120814||||||F'
		END
		ELSE IF @CLIENTID IN (14587)
		BEGIN
			SET @HL7VXUMessage = @HL7VXUMessage + 'ORC|RE||IZ-783278^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'						+ @SegmentTerminator + 'RXA|0|1|20120814||140^Influenza^CVX|0.5|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||W1356FE|20121214|SKB^GlaxoSmithKline^MVX|||CP|A'						+ @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|RA^Right Arm^HL70163'						+ @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V03^VFC eligible - Uninsured^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'						+ @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F'						+ @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||F'						+ @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'						+ @SegmentTerminator + 'ORC|RE||IZ-783276^NDA'						+ @SegmentTerminator + 'RXA|0|1|20110214||133^PCV 13^CVX|999|||01^Historical information - source unspecified^NIP001'						+ @SegmentTerminator + 'ORC|RE||IZ-783282^NDA|||||||||57422^RADON^NICHOLAS^^^^^^NDA^L'						+ @SegmentTerminator + 'RXA|0|1|20120814||110^DTaP-Hep B-IPV^CVX|0.5|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001||||||78HH34I|20121214|SKB^GlaxoSmithKline^MVX|||CP|A'						+ @SegmentTerminator + 'RXR|C28161^Intramuscular^NCIT|LA^Left Arm^HL70163'						+ @SegmentTerminator + 'OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V03^VFC eligible - Uninsured^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS'						+ @SegmentTerminator + 'OBX|2|CE|30956-7^vaccine type^LN|2|107^DTaP^CVX||||||F'						+ @SegmentTerminator + 'OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20070517||||||F'						+ @SegmentTerminator + 'OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F'						+ @SegmentTerminator + 'OBX|5|CE|30956-7^vaccine type^LN|3|89^Polio^CVX||||||F'						+ @SegmentTerminator + 'OBX|6|TS|29768-9^Date vaccine information statement published^LN|3|20111108||||||F'						+ @SegmentTerminator + 'OBX|7|TS|29769-7^Date vaccine information statement presented^LN|3|20120814||||||F'						+ @SegmentTerminator + 'OBX|8|CE|30956-7^vaccine type^LN|4|45^Hep B, unspecified formulation^CVX||||||F'						+ @SegmentTerminator + 'OBX|9|TS|29768-9^Date vaccine information statement published^LN|4|20120202||||||F'						+ @SegmentTerminator + 'OBX|10|TS|29769-7^Date vaccine information statement presented^LN|4|20120814||||||F'							
		END				 
								 
		UPDATE ClientImmunizations
		SET ExportedDateTime = Getdate()
		WHERE ClientImmunizationId IN (
				SELECT ClientImmunizationId
				FROM @ClientImmunizationIds
				)

		SELECT @HL7VXUMessage
	END TRY

	BEGIN CATCH
		DECLARE @Error VARCHAR(8000)

		SET @Error = CONVERT(VARCHAR, ERROR_NUMBER()) + '*****' + CONVERT(VARCHAR(4000), ERROR_MESSAGE()) + '*****' + ISNULL(CONVERT(VARCHAR, ERROR_PROCEDURE()), 'ssp_SCGetHL7ReportableImmunizationsExport') + '*****' + CONVERT(VARCHAR, ERROR_LINE()) + '*****' + CONVERT(VARCHAR, ERROR_SEVERITY()) + '*****' + CONVERT(VARCHAR, ERROR_STATE())

		RAISERROR (
				@Error
				,-- Message text.                                                                       
				16
				,-- Severity.                                                              
				1 -- State.                                                           
				);
	END CATCH
END
GO

