/****** Object:  StoredProcedure [dbo].[ssp_PrintClaimUB04]    Script Date: 08/17/2016 11:23:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[ssp_PrintClaimUB04]
    @ClaimBatchId INT = NULL ,
    @ClaimProcessId INT = NULL
/*********************************************************************
-- Stored Procedure: dbo.ssp_PrintClaimUB04
--
-- Copyright: 2006 Streamline Healthcare Solutions
-- Creation Date:  10.08.2013
--
-- Purpose: Selects data to print on UB04 claim form.
--          Either @ClaimBatchId or @ClaimProcessId has to be passed in.
--
-- Updates: 
--  Date         Author       Purpose
-- 10.08.2013    NJain        Created.
-- 08.17.2016	 NJain		  Updated to sort by DOS
-- 02.02.2018	 Vsinha		  Added the column for RDL 'UB04', use like Field67aPOA instead of the hard-coded "Y" in Field67DiagnosisCode for all diagnosis.
--                            for task:	Philhaven-Support #330  	
**********************************************************************/
AS
    SELECT DISTINCT
            --c.ClaimLineItemGroupId ,
            c.Field1ProviderName ,
            c.FieldProviderAddress ,
            c.FieldProviderCityStateZip ,
            c.FieldProviderTelephoneFax ,
            c.Field2PayToName ,
            c.Field2PayToAddress ,
            c.Field2PayToCityState ,
            c.Field3aPatientControlNumber ,
            c.Field3bMedicalRecordNumber ,
            c.Field4TypeOfBill ,
            c.Field5TaxIdType ,
            c.Field5TaxId ,
            c.Field6StatementFrom ,
            c.Field6StatementTo ,
            c.Field7Unlabelled ,
            c.Field8aPatientId ,
            c.Field8bPatientName ,
            c.Field9aPatientAddress ,
            c.Field9bCity ,
            c.Field9cState ,
            c.Field9dZip ,
            c.Field9eCountryCode ,
            c.Field10PatientDOB ,
            c.Field11PatientSex ,
            c.Field12AdmissionDate ,
            c.Field13AdmissionHour ,
            c.Field14AdmissionType ,
            c.Field15AdmissionSource ,
            c.Field16DischargeHour ,
            c.Field17DischargeStatus ,
            c.Field18ConditionCode ,
            c.Field19ConditionCode ,
            c.Field20ConditionCode ,
            c.Field21ConditionCode ,
            c.Field22ConditionCode ,
            c.Field23ConditionCode ,
            c.Field24ConditionCode ,
            c.Field25ConditionCode ,
            c.Field26ConditionCode ,
            c.Field27ConditionCode ,
            c.Field28ConditionCode ,
            c.Field29AccidentState ,
            c.Field30aUnlabelled ,
            c.Field30bUnlabelled ,
            c.Field31aOccurenceCode ,
            c.Field31aOccurenceDate ,
            c.Field31bOccurenceCode ,
            c.Field31bOccurenceDate ,
            c.Field32aOccurenceCode ,
            c.Field32aOccurenceDate ,
            c.Field32bOccurenceCode ,
            c.Field32bOccurenceDate ,
            c.Field33aOccurenceCode ,
            c.Field33aOccurenceDate ,
            c.Field33bOccurenceCode ,
            c.Field33bOccurenceDate ,
            c.Field34aOccurenceCode ,
            c.Field34aOccurenceDate ,
            c.Field34bOccurenceCode ,
            c.Field34bOccurenceDate ,
            c.Field35aOccuranceCode ,
            c.Field35aOccuranceFrom ,
            c.Field35aOccuranceTo ,
            c.Field35bOccuranceCode ,
            c.Field35bOccuranceFrom ,
            c.Field35bOccuranceTo ,
            c.Field36aOccuranceCode ,
            c.Field36aOccuranceFrom ,
            c.Field36aOccuranceTo ,
            c.Field36bOccuranceCode ,
            c.Field36bOccuranceFrom ,
            c.Field36bOccuranceTo ,
            c.Field37aUnlabelled ,
            c.Field37bUnlabelled ,
            c.Field38ResponsibleAddress1 ,
            c.Field38ResponsibleAddress2 ,
            c.Field38ResponsibleAddress3 ,
            c.Field38ResponsibleAddress4 ,
            c.Field38ResponsibleAddress5 ,
            c.Field39aValueCode ,
            c.Field39aValueAmountWhole ,
            c.Field39aValueDecimal ,
            c.Field39bValueCode ,
            c.Field39bValueAmountWhole ,
            c.Field39bValueDecimal ,
            c.Field39cValueCode ,
            c.Field39cValueAmountWhole ,
            c.Field39cValueDecimal ,
            c.Field39dValueCode ,
            c.Field39dValueAmountWhole ,
            c.Field39dValueDecimal ,
            c.Field40aValueCode ,
            c.Field40aValueAmountWhole ,
            c.Field40aValueDecimal ,
            c.Field40bValueCode ,
            c.Field40bValueAmountWhole ,
            c.Field40bValueDecimal ,
            c.Field40cValueCode ,
            c.Field40cValueAmountWhole ,
            c.Field40cValueDecimal ,
            c.Field40dValueCode ,
            c.Field40dValueAmountWhole ,
            c.Field40dValueDecimal ,
            c.Field41aValueCode ,
            c.Field41aValueAmountWhole ,
            c.Field41aValueDecimal ,
            c.Field41bValueCode ,
            c.Field41bValueAmountWhole ,
            c.Field41bValueDecimal ,
            c.Field41cValueCode ,
            c.Field41cValueAmountWhole ,
            c.Field41cValueDecimal ,
            c.Field41dValueCode ,
            c.Field41dValueAmountWhole ,
            c.Field41dValueDecimal ,
            c.Field42RevenueCode1 ,
            c.Field43RevenueDescription1 ,
            c.Field44HCPCSCode1 ,
            c.Field45ServiceDate1 ,
            c.Field46ServiceUnits1 ,
            c.Field47TotalChargesWhole1 ,
            c.Field47TotalChargesDecimal1 ,
            c.Field48NonCoveredChargesWhole1 ,
            c.Field48NonCoveredChargesDecimal1 ,
            c.Field49Unlabelled1 ,
            c.Field42RevenueCode2 ,
            c.Field43RevenueDescription2 ,
            c.Field44HCPCSCode2 ,
            c.Field45ServiceDate2 ,
            c.Field46ServiceUnits2 ,
            c.Field47TotalChargesWhole2 ,
            c.Field47TotalChargesDecimal2 ,
            c.Field48NonCoveredChargesWhole2 ,
            c.Field48NonCoveredChargesDecimal2 ,
            c.Field49Unlabelled2 ,
            c.Field42RevenueCode3 ,
            c.Field43RevenueDescription3 ,
            c.Field44HCPCSCode3 ,
            c.Field45ServiceDate3 ,
            c.Field46ServiceUnits3 ,
            c.Field47TotalChargesWhole3 ,
            c.Field47TotalChargesDecimal3 ,
            c.Field48NonCoveredChargesWhole3 ,
            c.Field48NonCoveredChargesDecimal3 ,
            c.Field49Unlabelled3 ,
            c.Field42RevenueCode4 ,
            c.Field43RevenueDescription4 ,
            c.Field44HCPCSCode4 ,
            c.Field45ServiceDate4 ,
            c.Field46ServiceUnits4 ,
            c.Field47TotalChargesWhole4 ,
            c.Field47TotalChargesDecimal4 ,
            c.Field48NonCoveredChargesWhole4 ,
            c.Field48NonCoveredChargesDecimal4 ,
            c.Field49Unlabelled4 ,
            c.Field42RevenueCode5 ,
            c.Field43RevenueDescription5 ,
            c.Field44HCPCSCode5 ,
            c.Field45ServiceDate5 ,
            c.Field46ServiceUnits5 ,
            c.Field47TotalChargesWhole5 ,
            c.Field47TotalChargesDecimal5 ,
            c.Field48NonCoveredChargesWhole5 ,
            c.Field48NonCoveredChargesDecimal5 ,
            c.Field49Unlabelled5 ,
            c.Field42RevenueCode6 ,
            c.Field43RevenueDescription6 ,
            c.Field44HCPCSCode6 ,
            c.Field45ServiceDate6 ,
            c.Field46ServiceUnits6 ,
            c.Field47TotalChargesWhole6 ,
            c.Field47TotalChargesDecimal6 ,
            c.Field48NonCoveredChargesWhole6 ,
            c.Field48NonCoveredChargesDecimal6 ,
            c.Field49Unlabelled6 ,
            c.Field42RevenueCode7 ,
            c.Field43RevenueDescription7 ,
            c.Field44HCPCSCode7 ,
            c.Field45ServiceDate7 ,
            c.Field46ServiceUnits7 ,
            c.Field47TotalChargesWhole7 ,
            c.Field47TotalChargesDecimal7 ,
            c.Field48NonCoveredChargesWhole7 ,
            c.Field48NonCoveredChargesDecimal7 ,
            c.Field49Unlabelled7 ,
            c.Field42RevenueCode8 ,
            c.Field43RevenueDescription8 ,
            c.Field44HCPCSCode8 ,
            c.Field45ServiceDate8 ,
            c.Field46ServiceUnits8 ,
            c.Field47TotalChargesWhole8 ,
            c.Field47TotalChargesDecimal8 ,
            c.Field48NonCoveredChargesWhole8 ,
            c.Field48NonCoveredChargesDecimal8 ,
            c.Field49Unlabelled8 ,
            c.Field42RevenueCode9 ,
            c.Field43RevenueDescription9 ,
            c.Field44HCPCSCode9 ,
            c.Field45ServiceDate9 ,
            c.Field46ServiceUnits9 ,
            c.Field47TotalChargesWhole9 ,
            c.Field47TotalChargesDecimal9 ,
            c.Field48NonCoveredChargesWhole9 ,
            c.Field48NonCoveredChargesDecimal9 ,
            c.Field49Unlabelled9 ,
            c.Field42RevenueCode10 ,
            c.Field43RevenueDescription10 ,
            c.Field44HCPCSCode10 ,
            c.Field45ServiceDate10 ,
            c.Field46ServiceUnits10 ,
            c.Field47TotalChargesWhole10 ,
            c.Field47TotalChargesDecimal10 ,
            c.Field48NonCoveredChargesWhole10 ,
            c.Field48NonCoveredChargesDecimal10 ,
            c.Field49Unlabelled10 ,
            c.Field42RevenueCode11 ,
            c.Field43RevenueDescription11 ,
            c.Field44HCPCSCode11 ,
            c.Field45ServiceDate11 ,
            c.Field46ServiceUnits11 ,
            c.Field47TotalChargesWhole11 ,
            c.Field47TotalChargesDecimal11 ,
            c.Field48NonCoveredChargesWhole11 ,
            c.Field48NonCoveredChargesDecimal11 ,
            c.Field49Unlabelled11 ,
            c.Field42RevenueCode12 ,
            c.Field43RevenueDescription12 ,
            c.Field44HCPCSCode12 ,
            c.Field45ServiceDate12 ,
            c.Field46ServiceUnits12 ,
            c.Field47TotalChargesWhole12 ,
            c.Field47TotalChargesDecimal12 ,
            c.Field48NonCoveredChargesWhole12 ,
            c.Field48NonCoveredChargesDecimal12 ,
            c.Field49Unlabelled12 ,
            c.Field42RevenueCode13 ,
            c.Field43RevenueDescription13 ,
            c.Field44HCPCSCode13 ,
            c.Field45ServiceDate13 ,
            c.Field46ServiceUnits13 ,
            c.Field47TotalChargesWhole13 ,
            c.Field47TotalChargesDecimal13 ,
            c.Field48NonCoveredChargesWhole13 ,
            c.Field48NonCoveredChargesDecimal13 ,
            c.Field49Unlabelled13 ,
            c.Field42RevenueCode14 ,
            c.Field43RevenueDescription14 ,
            c.Field44HCPCSCode14 ,
            c.Field45ServiceDate14 ,
            c.Field46ServiceUnits14 ,
            c.Field47TotalChargesWhole14 ,
            c.Field47TotalChargesDecimal14 ,
            c.Field48NonCoveredChargesWhole14 ,
            c.Field48NonCoveredChargesDecimal14 ,
            c.Field49Unlabelled14 ,
            c.Field42RevenueCode15 ,
            c.Field43RevenueDescription15 ,
            c.Field44HCPCSCode15 ,
            c.Field45ServiceDate15 ,
            c.Field46ServiceUnits15 ,
            c.Field47TotalChargesWhole15 ,
            c.Field47TotalChargesDecimal15 ,
            c.Field48NonCoveredChargesWhole15 ,
            c.Field48NonCoveredChargesDecimal15 ,
            c.Field49Unlabelled15 ,
            c.Field42RevenueCode16 ,
            c.Field43RevenueDescription16 ,
            c.Field44HCPCSCode16 ,
            c.Field45ServiceDate16 ,
            c.Field46ServiceUnits16 ,
            c.Field47TotalChargesWhole16 ,
            c.Field47TotalChargesDecimal16 ,
            c.Field48NonCoveredChargesWhole16 ,
            c.Field48NonCoveredChargesDecimal16 ,
            c.Field49Unlabelled16 ,
            c.Field42RevenueCode17 ,
            c.Field43RevenueDescription17 ,
            c.Field44HCPCSCode17 ,
            c.Field45ServiceDate17 ,
            c.Field46ServiceUnits17 ,
            c.Field47TotalChargesWhole17 ,
            c.Field47TotalChargesDecimal17 ,
            c.Field48NonCoveredChargesWhole17 ,
            c.Field48NonCoveredChargesDecimal17 ,
            c.Field49Unlabelled17 ,
            c.Field42RevenueCode18 ,
            c.Field43RevenueDescription18 ,
            c.Field44HCPCSCode18 ,
            c.Field45ServiceDate18 ,
            c.Field46ServiceUnits18 ,
            c.Field47TotalChargesWhole18 ,
            c.Field47TotalChargesDecimal18 ,
            c.Field48NonCoveredChargesWhole18 ,
            c.Field48NonCoveredChargesDecimal18 ,
            c.Field49Unlabelled18 ,
            c.Field42RevenueCode19 ,
            c.Field43RevenueDescription19 ,
            c.Field44HCPCSCode19 ,
            c.Field45ServiceDate19 ,
            c.Field46ServiceUnits19 ,
            c.Field47TotalChargesWhole19 ,
            c.Field47TotalChargesDecimal19 ,
            c.Field48NonCoveredChargesWhole19 ,
            c.Field48NonCoveredChargesDecimal19 ,
            c.Field49Unlabelled19 ,
            c.Field42RevenueCode20 ,
            c.Field43RevenueDescription20 ,
            c.Field44HCPCSCode20 ,
            c.Field45ServiceDate20 ,
            c.Field46ServiceUnits20 ,
            c.Field47TotalChargesWhole20 ,
            c.Field47TotalChargesDecimal20 ,
            c.Field48NonCoveredChargesWhole20 ,
            c.Field48NonCoveredChargesDecimal20 ,
            c.Field49Unlabelled20 ,
            c.Field42RevenueCode21 ,
            c.Field43RevenueDescription21 ,
            c.Field44HCPCSCode21 ,
            c.Field45ServiceDate21 ,
            c.Field46ServiceUnits21 ,
            c.Field47TotalChargesWhole21 ,
            c.Field47TotalChargesDecimal21 ,
            c.Field48NonCoveredChargesWhole21 ,
            c.Field48NonCoveredChargesDecimal21 ,
            c.Field49Unlabelled21 ,
            c.Field42RevenueCode22 ,
            c.Field43RevenueDescription22 ,
            c.Field44HCPCSCode22 ,
            c.Field45ServiceDate22 ,
            c.Field46ServiceUnits22 ,
            c.Field47TotalChargesWhole22 ,
            c.Field47TotalChargesDecimal22 ,
            c.Field48NonCoveredChargesWhole22 ,
            c.Field48NonCoveredChargesDecimal22 ,
            c.Field49Unlabelled22 ,
            c.Field43PageNumber ,
            c.Field43PageOf ,
            c.Field44CreationDate ,
            c.Field47TotalChargesWhole23 ,
            c.Field47TotalChargesDecimal23 ,
            c.Field48NonCoveredChargesWhole23 ,
            c.Field48NonCoveredChargesDecimal23 ,
            c.Field50aPayerName ,
            c.Field50bPayerName ,
            c.Field50cPayerName ,
            c.Field51aHealthPlanId ,
            c.Field51bHealthPlanId ,
            c.Field51cHealthPlanId ,
            c.Field52aReleaseOfInformation ,
            c.Field52bReleaseOfInformation ,
            c.Field52cReleaseOfInformation ,
            c.Field53aAssignmentOfBenefits ,
            c.Field53bAssignmentOfBenefits ,
            c.Field53cAssignmentOfBenefits ,
            c.Field54aPriorPaymentsWhole ,
            c.Field54aPriorPaymentsDecimal ,
            c.Field54bPriorPaymentsWhole ,
            c.Field54bPriorPaymentsDecimal ,
            c.Field54cPriorPaymentsWhole ,
            c.Field54cPriorPaymentsDecimal ,
            c.Field55aEstimatedAmountWhole ,
            c.Field55aEstimatedAmountDecimal ,
            c.Field55bEstimatedAmountWhole ,
            c.Field55bEstimatedAmountDecimal ,
            c.Field55cEstimatedAmountWhole ,
            c.Field55cEstimatedAmountDecimal ,
            c.Field56FacilityNPI ,
            c.Field57aOtherProviderId ,
            c.Field57bOtherProviderId ,
            c.Field57cOtherProviderId ,
            c.Field58aInsuredName ,
            c.Field58bInsuredName ,
            c.Field58cInsuredName ,
            c.Field59aPatientRelationship ,
            c.Field59bPatientRelationship ,
            c.Field59cPatientRelationship ,
            c.Field60aInsuredId ,
            c.Field60bInsuredId ,
            c.Field60cInsuredId ,
            c.Field61aGroupName ,
            c.Field61bGroupName ,
            c.Field61cGroupName ,
            c.Field62aGroupNumber ,
            c.Field62bGroupNumber ,
            c.Field62cGroupNumber ,
            c.Field63aAuthorizationCode ,
            c.Field63bAuthorizationCode ,
            c.Field63cAuthorizationCode ,
            c.Field64aDocumentControlNumber ,
            c.Field64bDocumentControlNumber ,
            c.Field64cDocumentControlNumber ,
            c.Field65aEmployerName ,
            c.Field65bEmployerName ,
            c.Field65cEmployerName ,
             CASE WHEN CAST(RIGHT(Field6StatementTo, 2) + LEFT(Field6StatementTo, 4) AS DATE) <= '9/30/2015' THEN '9'  
                 ELSE '10'  
            END AS Field66DiagnosisVersion ,  
              
            --c.Field66DiagnosisVersion ,  
             c.Field67PrincipalDiagnosis ,
            c.Field67POA,  
            c.Field67aOtherDiagnosis ,  
            c.Field67aPOA,
            c.Field67bOtherDiagnosis ,  
            c.Field67bPOA,
            c.Field67cOtherDiagnosis ,
            c.Field67cPOA,
            c.Field67dOtherDiagnosis , 
            c.Field67dPOA,
            c.Field67eOtherDiagnosis , 
            c.Field67ePOA,
            c.Field67fOtherDiagnosis ,  
            c.Field67fPOA,
            c.Field67gOtherDiagnosis , 
            c.Field67gPOA,
            c.Field67hOtherDiagnosis ,  
            c.Field67hPOA,
            c.Field67iOtherDiagnosis ,  
            c.Field67iPOA,
            c.Field67jOtherDiagnosis ,  
            c.Field67jPOA,
            c.Field67kOtherDiagnosis ,  
            c.Field67kPOA,
            c.Field67lOtherDiagnosis ,  
            c.Field67lPOA,
            c.Field67mOtherDiagnosis ,  
            c.Field67mPOA,
            c.Field67nOtherDiagnosis ,  
            c.Field67nPOA,
            c.Field67oOtherDiagnosis , 
            c.Field67oPOA,
            c.Field67pOtherDiagnosis ,  
            c.Field67pPOA,
            c.Field67qOtherDiagnosis , 
            c.Field67qPOA,
            c.Field68aUnlabelled ,
            c.Field68bUnlabelled ,
            c.Field69AdmittingDiagnosis ,
            c.Field70aReasonForVisitCode ,
            c.Field70bReasonForVisitCode ,
            c.Field70cReasonForVisitCode ,
            c.Field71PPSCode ,
            c.Field72aECICode ,
            c.Field72bECICode ,
            c.Field72cECICode ,
            c.Field73Unlabelled ,
            c.Field74PrincipalProcedureCode ,
            c.Field74PrincipalProcedureDate ,
            c.Field74aOtherProcedureCode ,
            c.Field74aOtherProcedureDate ,
            c.Field74bOtherProcedureCode ,
            c.Field74bOtherProcedureDate ,
            c.Field74cOtherProcedureCode ,
            c.Field74cOtherProcedureDate ,
            c.Field74dOtherProcedureCode ,
            c.Field74dOtherProcedureDate ,
            c.Field74eOtherProcedureCode ,
            c.Field74eOtherProcedureDate ,
            c.Field75aUnlabelled ,
            c.Field75bUnlabelled ,
            c.Field75cUnlabelled ,
            c.Field75dUnlabelled ,
            c.Field76AttendingNPI ,
            c.Field76AttendingQualifier ,
            c.Field76AttendingProviderId ,
            c.Field76AttendingLastName ,
            c.Field76AttendingFirstName ,
            c.Field77OperatingNPI ,
            c.Field77OperatingQualifier ,
            c.Field77OperatingProviderId ,
            c.Field77OperatingLastName ,
            c.Field77OperatingFirstName ,
            c.Field78OtherType ,
            c.Field78OtherNPI ,
            c.Field78OtherQualifier ,
            c.Field78OtherProviderId ,
            c.Field78OtherLastName ,
            c.Field78OtherFirstName ,
            c.Field79OtherType ,
            c.Field79OtherNPI ,
            c.Field79OtherQualifier ,
            c.Field79OtherProviderId ,
            c.Field79OtherLastName ,
            c.Field79OtherFirstName ,
            c.Field80aRemarks ,
            c.Field80bRemarks ,
            c.Field80cRemarks ,
            c.Field80dRemarks ,
            c.Field81aQualifier ,
            c.Field81aCode ,
            c.Field81aValue ,
            c.Field81bQualifier ,
            c.Field81bCode ,
            c.Field81bValue ,
            c.Field81cQualifier ,
            c.Field81cCode ,
            c.Field81cValue ,
            c.Field81dQualifier ,
            c.Field81dCode ,
            c.Field81dValue ,
            clig.ClientId ,
            cli.DateOfService, 
            clig.ClaimLineItemGroupId
    FROM    ClaimUB04s c
            JOIN ClaimLineItemGroups clig ON clig.ClaimLineItemGroupId = c.ClaimLineItemGroupId
            JOIN ClaimBatches cb ON cb.ClaimBatchId = clig.ClaimBatchId
            JOIN ClaimLineItems cli ON cli.ClaimLineItemGroupId = clig.ClaimLineItemGroupId
    WHERE   ( cb.ClaimBatchId = @ClaimBatchId
              OR cb.ClaimProcessId = @ClaimProcessId
            )
            AND ISNULL(clig.RecordDeleted, 'N') = 'N'
            AND ISNULL(cli.RecordDeleted, 'N') = 'N'
            AND ISNULL(c.RecordDeleted, 'N') = 'N'
    ORDER BY clig.ClientId ,
            cli.DateOfService ,
            clig.ClaimLineItemGroupId

GO
