DECLARE @TEMPCLIENT TABLE (
  CLIENTID int
)
DELETE FROM @TEMPCLIENT
INSERT INTO @TEMPCLIENT (CLIENTID)
  VALUES (60097)
INSERT INTO @TEMPCLIENT (CLIENTID)
  VALUES (60099)

--SELECT * FROM @TEMPCLIENT
DECLARE @CLIENTID int


DECLARE #DUPLICATIONREMOVETOGETCLIENTID CURSOR FOR
SELECT
  CLIENTID
FROM @TEMPCLIENT
OPEN #DUPLICATIONREMOVETOGETCLIENTID
FETCH #DUPLICATIONREMOVETOGETCLIENTID INTO @CLIENTID
WHILE @@fetch_status = 0
BEGIN
  DECLARE @HEALTHRECORDDATE datetime
  SELECT
    CAST(@CLIENTID AS varchar) + '============================CLIENTID CHANGED===================================='
  DECLARE #FINALSTAGEOFREMOVEDUPLICATION CURSOR FOR
  SELECT DISTINCT
    HealthRecordDate
  FROM ClientHealthDataAttributes
  WHERE CLIENTID = @CLIENTID
  AND ISNULL(RecordDeleted, 'N') = 'N'
  OPEN #FINALSTAGEOFREMOVEDUPLICATION
  FETCH #FINALSTAGEOFREMOVEDUPLICATION INTO @HEALTHRECORDDATE

  WHILE @@FETCH_STATUS = 0
  BEGIN
    --select @HEALTHRECORDDATE
    ;
    WITH duplicates
    AS (SELECT
      ClientHealthDataAttributeId,
      HealthDataAttributeId,
      HealthRecordDate,
      ClientId,
      HealthDataSubTemplateId,
      RecordDeleted,
      DeletedDate,
      DeletedBy,
      VALUE,
      ROW_NUMBER() OVER (PARTITION BY HealthDataAttributeId, HealthDataSubTemplateId order by Value DESC) AS num 
    FROM ClientHealthDataAttributes
    WHERE ClientId = @CLIENTID
    AND HealthRecordDate = @HEALTHRECORDDATE 
    AND ISNULL(RecordDeleted, 'N') = 'N')
   
    UPDATE duplicates
    SET RecordDeleted = 'Y',
        DeletedDate = GETDATE(),
        DeletedBy = 'HDDATACORRECTION'
    WHERE num > 1
    AND VALUE IS NULL
    --select * from duplicates where num>1 AND VALUE IS NULL

    FETCH #FINALSTAGEOFREMOVEDUPLICATION INTO @HEALTHRECORDDATE
  END
  CLOSE #FINALSTAGEOFREMOVEDUPLICATION
  DEALLOCATE #FINALSTAGEOFREMOVEDUPLICATION

  FETCH #DUPLICATIONREMOVETOGETCLIENTID INTO @CLIENTID
END
CLOSE #DUPLICATIONREMOVETOGETCLIENTID
DEALLOCATE #DUPLICATIONREMOVETOGETCLIENTID