-- SWMBH - SUPPORT TASK # 1124
IF EXISTS (SELECT 1 FROM GLOBALCODECATEGORIES WHERE CATEGORY='LICENSETYPE')
BEGIN
UPDATE GLOBALCODECATEGORIES
SET USERDEFINEDCATEGORY = 'N'
WHERE CATEGORY ='LICENSETYPE'
END
GO