UPDATE DocumentCodes SET ViewStoredProcedure='ssp_RDLClientPrescriptionFax' WHERE DocumentCodeId=501
UPDATE DocumentCodes SET ViewStoredProcedure='ssp_RDLClientPrescriptionMain' WHERE DocumentCodeId=502
UPDATE DocumentCodes SET ViewStoredProcedure='ssp_RDLClientPrescriptionSurescripts' WHERE DocumentCodeId=1471