-- MSOOD 4/20/2017 PATHWAY - SUPPORT GO LIVE 159
Delete from GlobalSubCodes where GLOBALCODEID=5403 AND SUBCODENAME='Assigned'

IF NOT EXISTS(SELECT 1
	FROM GLOBALSUBCODES
	WHERE GLOBALCODEID=5403 AND SUBCODENAME='Assigned'
		AND ISNULL(RECORDDELETED,'N')='N')
BEGIN
	SET IDENTITY_INSERT GLOBALSUBCODES ON
	INSERT INTO GLOBALSUBCODES ( GlobalSubCodeId,GLOBALCODEID, SUBCODENAME, CODE, ACTIVE, CANNOTMODIFYNAMEORDELETE, SORTORDER )
	Select 4101
	,	   5403
	,      'Assigned'
	,      'AS'
	,      'Y'
	,      'N'
	,      10
	SET IDENTITY_INSERT GLOBALSUBCODES OFF
END
ELSE
UPdate GLOBALSUBCODES Set SUBCODENAME='Assigned',CODE='AS' WHERE GLOBALCODEID=5403 AND SUBCODENAME='ASSIGNED'
GO

IF EXISTS(SELECT *
	FROM SCREENS
	WHERE DOCUMENTCODEID = 1620)
BEGIN
	UPDATE SCREENS
	SET VALIDATIONSTOREDPROCEDUREUPDATE = 'SSP_POSTUPDATECAREPLANPROGRAMDOCUMENTASSIGNEDTASKS'
	WHERE DOCUMENTCODEID = 1620
END
GO
