-------Task #3 in New Directions - Customizations --- InsertScript_RiskDFA.sql -------------

--Task #3 in New Directions - Customizations


-- Mental Status

IF NOT EXISTS (SELECT * FROM forms WHERE formid = 3) BEGIN SET IDENTITY_INSERT dbo.forms ON INSERT INTO forms(formid, formname, TableName, TotalNumberOfColumns, Active, RetrieveStoredProcedure) values(3,'PreScreen Mental Status','CustomAcuteServicesPrescreens',1,'Y','') SET IDENTITY_INSERT dbo.forms OFF END

IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 8) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(8,3,1,NULL,'<b>Orientation</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 9) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(9,3,2,NULL,'<b>Level of Consciousness</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 11) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(11,3,4,NULL,'<b>Mood</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 13) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(13,3,6,NULL,'<b>Affect</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 15) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(15,3,8,NULL,'<b>Thought Processing</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 18) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(18,3,11,NULL,'<b>Speech</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 19) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(19,3,12,NULL,'<b>Judgment</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 21) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(21,3,14,NULL,'<b>Impulsivity</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 23) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(23,3,16,NULL,'<b>Insight about Illness and Behavior</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 33) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(33,3,20,NULL,'<b>Others</b>','Y',NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.FormSections OFF END

IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 18) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(18,8,1,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 19) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(19,9,2,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 20) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(20,9,3,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 21) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(21,11,4,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 22) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(22,11,5,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 23) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(23,13,6,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 24) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(24,13,7,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 25) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(25,15,8,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 26) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(26,15,10,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 27) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(27,15,9,NULL,'Y',NULL,NULL,NULL,6) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 28) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(28,18,11,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 29) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(29,19,12,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 30) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(30,19,13,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 31) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(31,21,14,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 32) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(32,21,15,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 33) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(33,23,16,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 34) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(34,33,17,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 35) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(35,33,18,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END

IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 48) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(48,8,18,'5362','Person',1,'Y',NULL,'MentalStatusOrientaionPerson','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 49) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(49,8,18,'5362','Place',1,'Y',NULL,'MentalStatusOrientaionPlace','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 50) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(50,8,18,'5362','Time',1,'Y',NULL,'MentalStatusOrientaionTime','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 51) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(51,8,18,'5362','Circumstances/Situation',1,'Y',NULL,'MentalStatusOrientaionCircumstance','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 52) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(52,9,19,'5362','Alert',1,'Y',NULL,'MentalStatusLOCAlert','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 53) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(53,9,19,'5362','Sedate',1,'Y',NULL,'MentalStatusLOCSedate','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 54) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(54,9,19,'5362','Lethargic',1,'Y',NULL,'MentalStatusLOCLethargic','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 55) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(55,9,19,'5362','Obtunded',1,'Y',NULL,'MentalStatusLOCObtunded','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 56) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(56,9,20,'5362','Other',1,'Y',NULL,'MentalStatusLOCOther','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 57) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(57,9,20,'5363','',1,'Y',NULL,'MentalStatusLOCOtherDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 58) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(58,11,21,'5362','Appropriate',1,'Y',NULL,'MentaStatusMoodAppropriate','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 59) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(59,11,21,'5362','Incongurent',1,'Y',NULL,'MentaStatusMoodIncongruent','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 60) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(60,11,21,'5362','Hostile/Angry',1,'Y',NULL,'MentaStatusMoodHostile','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 61) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(61,11,21,'5362','Tearful',1,'Y',NULL,'MentaStatusMoodTearful','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 62) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(62,11,22,'5362','Other',1,'Y',NULL,'MentaStatusMoodOther','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 63) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(63,11,22,'5363','',1,'Y',NULL,'MentaStatusMoodOtherDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 64) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(64,13,23,'5362','Restricted',1,'Y',NULL,'MentaStatusAffectRestricted','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 65) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(65,13,23,'5362','Unremarkable',1,'Y',NULL,'MentaStatusAffectUnremarkable','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 66) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(66,13,23,'5362','Expansive',1,'Y',NULL,'MentaStatusAffectExpansive','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 67) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(67,13,24,'5362','Other',1,'Y',NULL,'MentaStatusAffectOther','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 68) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(68,13,24,'5363','',1,'Y',NULL,'MentaStatusAffectOtherDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 69) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(69,15,25,'5362','Lucid/rational',1,'Y',NULL,'MentaStatusThoughtLucid','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 70) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(70,15,25,'5362','Suscpicious/paranoid',1,'Y',NULL,'MentaStatusThoughtSuspicious','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 71) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(71,15,25,'5362','Obsessive',1,'Y',NULL,'MentaStatusThoughtObsessive','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 72) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(72,15,26,'5363','',2,'Y',NULL,'MentaStatusThoughtObsessiveAbout','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 119) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(119,15,27,'5362','Tangential',1,'Y',NULL,'MentaStatusThoughtTangential','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 120) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(120,15,27,'5362','Loose',1,'Y',NULL,'MentaStatusThoughtLoose','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 121) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(121,15,27,'5362','Delusional',1,'Y',NULL,'MentaStatusThoughtDelusional','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 122) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(122,15,27,'5362','Psychosis',1,'Y',NULL,'MentaStatusThoughtPsychosis','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 123) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(123,15,27,'5362','Impoverished',1,'Y',NULL,'MentaStatusThoughtImpoverished','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 124) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(124,15,27,'5362','Confused',1,'Y',NULL,'MentaStatusThoughtConfused','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 125) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(125,18,28,'5362','Clear',1,'Y',NULL,'MentaStatusSpeechClear','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 126) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(126,18,28,'5362','Rapid/Pressured',1,'Y',NULL,'MentaStatusSpeechRapid','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 127) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(127,18,28,'5362','Slurred',1,'Y',NULL,'MentaStatusSpeechSlurred','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 128) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(128,19,29,'5365','',1,'Y','XDFINTACT           ','MentaStatusJudgementImpaired','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 129) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(129,19,29,'5365','',1,'N','XDFINTACT           ','MentaStatusJudgementImpaired','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 130) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(130,19,30,'5363','',2,'Y',NULL,'MentaStatusJudgementImpairedDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 131) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(131,21,31,'5365','',1,'Y','XDFAPPARENT         ','MentalStatusImpulsivityApparent','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 132) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(132,21,31,'5365','',1,'N','XDFAPPARENT         ','MentalStatusImpulsivityApparent','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 133) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(133,21,32,'5363','',2,'Y',NULL,'MentalStatusImpulsivityApparentDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 134) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(134,23,33,'5365','',1,'N','XDFGOOD             ','MentalStatusInsightLimited','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 135) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(135,23,33,'5365','',1,'Y','XDFGOOD             ','MentalStatusInsightLimited','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 136) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(136,33,34,'5362','Px with grooming/hygiene',1,'Y',NULL,'MentalStatusPxWithGrooming','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 137) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(137,33,34,'5362','Sleep disturbance',2,'Y',NULL,'MentalStatusSleepDisturbance','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 138) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(138,33,34,'5363','(Describe)',3,'Y',NULL,'MentalStatusSleepDisturbanceDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 139) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(139,33,35,'5362','Eating disturbance (weight gain/loss)',4,'Y',NULL,'MentalStatusEatingDisturbance','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 140) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(140,33,35,'5366','',5,'Y',NULL,'MentalStatusEatingDisturbanceLbs','N',NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 141) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(141,33,35,'5362','Not medication compliant',7,'Y',NULL,'MentalStatusNotMedicationComplaint','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 168) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(168,23,33,'5363','',3,'Y',NULL,'MentalStatusInsightLimitedDescribe','N',NULL,780,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1287) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1287,15,26,'5374','(about)',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1288) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1288,19,30,'5374','Describe',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1289) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1289,21,32,'5374','Describe',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1290) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1290,23,33,'5374','Describe',2,'N',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1560) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1560,33,35,'5374','lbs',6,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
GO


--Recommendations/Summary

IF NOT EXISTS (SELECT * FROM forms WHERE formid = 39) BEGIN SET IDENTITY_INSERT dbo.forms ON INSERT INTO forms(formid, formname, TableName, TotalNumberOfColumns, Active, RetrieveStoredProcedure) values(39,'PreScreen Summary','CustomAcuteServicesPrescreens',1,'Y','') SET IDENTITY_INSERT dbo.forms OFF END

IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 190) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(190,39,1,NULL,'Screener Recommendations','Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 191) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(191,39,2,NULL,'<b>Rights Notification</b>','Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSections OFF END
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 192) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(192,39,3,NULL,'<b>Summary</b>','Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSections OFF END

IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 330) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(330,190,1,NULL,'Y',NULL,NULL,NULL,6) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 331) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(331,190,2,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 332) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(332,190,3,NULL,'Y',NULL,NULL,NULL,7) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 333) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(333,190,4,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 334) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(334,190,5,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 335) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(335,191,1,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 336) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(336,191,2,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 337) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(337,191,3,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 338) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(338,191,4,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 339) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(339,191,5,NULL,'Y',NULL,NULL,NULL,4) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 340) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(340,191,6,NULL,'Y',NULL,NULL,NULL,3) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 341) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(341,192,1,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 342) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(342,192,2,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 343) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(343,192,3,NULL,'Y',NULL,NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END

IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1300) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1300,190,330,'5362','Voluntary',1,'Y',NULL,'SummaryVoluntary','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1301) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1301,190,330,'5362','Involuntary',2,'Y',NULL,'SummaryInvoluntary','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1302) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1302,190,330,'5374','Inpatient Facility Name',4,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1304) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1304,190,330,'5363','',5,'Y',NULL,'SummaryInpatientFacilityName','N',NULL,171,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1305) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1305,190,330,'5374','Authorized Days',5,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1306) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1306,190,330,'5372','',6,'Y',NULL,'AuthorizedDays','N',NULL,235,NULL,'S',NULL,'ssp_SCGetDays','DayValue','DayName',NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1307) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1307,190,331,'5362','Crisis Residential',1,'Y',NULL,'SummaryCrisisResidential','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1308) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1308,190,331,'5374','Program Name',2,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1309) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1309,190,331,'5363','',3,'Y',NULL,'SummaryCrisisFacilityName','N',NULL,550,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1310) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1310,190,331,'5362','Partial Hospitalization',4,'Y',NULL,'SummaryPartialHospitalization','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1311) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1311,190,331,'5374','Facility Name',5,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1312) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1312,190,331,'5363','',6,'Y',NULL,'SummaryPartialFacilityName','N',NULL,550,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1313) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1313,190,332,'5362','ACT',1,'Y',NULL,'SummaryACT','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1314) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1314,190,332,'5362','Case Mgt.',2,'Y',NULL,'SummaryCaseManagement','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1315) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1315,190,332,'5362','IOP',3,'Y',NULL,'SummaryIOP','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1316) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1316,190,332,'5362','Outpatient',4,'Y',NULL,'SummaryOutpatient','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1317) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1317,190,332,'5362','Substance Abuse',5,'Y',NULL,'SummarySubstanceAbuse','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1318) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1318,190,332,'5362','Other (specify)',6,'Y',NULL,'SummaryOther','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1319) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1319,190,332,'5363','',7,'Y',NULL,'SummaryOtherSpecify','N',NULL,338,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1320) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1320,190,333,'5374','Provider recommended',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1322) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1322,190,333,'5363','',2,'Y',NULL,'SummaryProviderRecommended','N',NULL,636,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1323) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1323,190,334,'5374','Family Notification Acute Services offered',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1324) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1324,190,334,'5365','',2,'Y','RADIOYN             ','SummaryFamilyNotificationOffered','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1325) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1325,190,334,'5374','Family member’s Name',3,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1326) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1326,190,334,'5361','',4,'Y',NULL,'SummaryFamilyMemberName','N',NULL,359,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1328) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1328,191,335,'5365','Was Inpatient treatment requested by consumer/legal guardian and then denied',1,'Y','RADIOYN             ','SummaryInpatientRequestedAndDenied','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1329) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1329,191,335,'5365','If Yes, was Second Opinion Rights explained/given',2,'Y','RADIOYN             ','SummarySecondOpinionRights','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1332) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1332,191,336,'5365','Was consumer offered alternative services?',1,'Y','RADIOYN             ','SummaryOfferedAlternativeServices','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1333) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1333,191,336,'5374','&nbsp;&nbsp;If Yes, specify',2,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1334) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1334,191,336,'5363','',3,'Y',NULL,'SummaryAlternativeServicesSpecify','N',NULL,382,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1336) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1336,191,337,'5365','Consumer agreed to alternative services',1,'Y','RADIOYN             ','SummaryAgreedToAlternativeServices','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1337) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1337,191,337,'5374','&nbsp;&nbsp;If yes, please complete the following:',2,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1338) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1338,191,338,'5367','',2,'Y',NULL,'SummaryAlternativeAppointmentTime','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1339) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1339,191,338,'5369','Time of Appointment',3,'Y',NULL,'SummaryAlternativeAppointmentTime','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1340) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1340,191,339,'5363','',2,'Y',NULL,'SummaryAlternativeAgencyName','N',NULL,365,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1341) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1341,191,339,'5361','Contact',3,'Y',NULL,'SummaryAlternativeAgencyContactNumber','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1342) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1342,191,338,'5374','Date of Appointment',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1343) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1343,191,339,'5374','Agency Name',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1344) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1344,191,340,'5365','Did Consumer choose alternative plan other than services offered',1,'Y','RADIOYN             ','SummaryChooseOtherPlan','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1345) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1345,191,340,'5374','&nbsp;&nbsp;If yes, specify',2,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1346) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1346,191,340,'5363','',3,'Y',NULL,'SummaryChooseOtherPlanSpecify','N',NULL,277,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1347) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1347,191,340,'5365','Was adequate notice of rights given?',4,'Y','RADIOYN             ','SummaryMedicaidRights','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1348) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1348,191,340,'5363','',6,'Y',NULL,'SummaryMedicaidRightsWhyNot','N',NULL,277,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1349) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1349,191,340,'5374','If no, why?',5,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1350) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1350,192,341,'5362','Consumer refused treatment',1,'Y',NULL,'SummaryRefusedTreatment','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1351) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1351,192,341,'5362','Crisis Resolved/No services needed at this time',2,'Y',NULL,'SummaryNoServicesNeeded','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1352) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1352,192,341,'5362','Unable to obtain consumer signature.',3,'Y',NULL,'SummaryUnableToObtainSignature','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1353) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1353,192,341,'5362','Consumer signed paper copy',4,'Y',NULL,'ClientSignedPaperCopy','N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1354) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1354,192,342,'5374','If unable to obtain, provide rationale:',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1355) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1355,192,342,'5363','',2,'Y',NULL,'SummaryUnableToObtainSignatureReason','N',NULL,564,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1356) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1356,192,343,'5374','Summary',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 1357) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(1357,192,343,'5363','',2,'Y',NULL,'SummarySummary','N',NULL,751,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END

GO