
/********************************************************************************************
Author		:	Aravind
CreatedDate	:	13 Oct 2014
Purpose		:	FormId = 85 - DFA forms inser script to generate Program Enrollment tab of Registration Document
*********************************************************************************************/

DELETE FROM FormItems WHERE FormSectionId in (SELECT FormSectionId FROM FormSections WHERE FormId = 85)
DELETE FROM FormSectionGroups WHERE FormSectionId in (SELECT FormSectionId FROM FormSections WHERE FormId = 85)
DELETE FROM FormSections WHERE FormId = 85
DELETE FROM Forms WHERE FormId = 85

/*-------Forms Start-------*/
IF NOT EXISTS (SELECT * FROM forms WHERE formid = 85) BEGIN SET IDENTITY_INSERT dbo.forms ON INSERT INTO forms(formid, formname, TableName, TotalNumberOfColumns, Active, RetrieveStoredProcedure,JavascriptFilePath) values(85,'Admission Document','CustomDocumentRegistrations',1,'Y','','Custom/Admission/Scripts/RegistrationDocument.js') SET IDENTITY_INSERT dbo.forms OFF END
/*-------Forms End-------*/

/*-------FormSections Start--------*/
IF NOT EXISTS (SELECT * FROM FormSections WHERE FormSectionId = 300) BEGIN SET IDENTITY_INSERT dbo.FormSections ON INSERT INTO dbo.FormSections(FormSectionId, formid, SortOrder, PlaceOnTopOfPage, SectionLabel, Active, SectionEnableCheckBox, SectionEnableCheckBoxText, SectionEnableCheckBoxColumnName, NumberOfColumns) values(300,85,1,NULL,'Program Enrollment','Y','N',NULL,NULL,1) SET IDENTITY_INSERT dbo.FormSections OFF END
/*-------FormSections End--------*/

/*-------FormSectionGroups Start--------*/
IF NOT EXISTS (SELECT * FROM FormSectionGroups WHERE FormSectionGroupId = 771) BEGIN SET IDENTITY_INSERT dbo.FormSectionGroups ON INSERT INTO dbo.FormSectionGroups (FormSectionGroupId, formsectionid, SortOrder, GroupLabel, Active, GroupEnableCheckBox, GroupEnableCheckBoxText, GroupEnableCheckBoxColumnName,  NumberOfItemsInRow) VALUES(771,300,1,NULL,'Y',NULL,NULL,NULL,2) SET IDENTITY_INSERT dbo.FormSectionGroups OFF END
/*-------FormSectionGroups End--------*/

/*-------FormItems Start--------*/
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3324) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3324,300,771,'5374','Primary Program',1,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3325) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3325,300,771,'5372','',2,'Y',NULL,'PrimaryProgramId','N',NULL,200,NULL,'S',NULL,'csp_GetActiveProgramName','ProgramId','ProgramName',NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END

IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3334) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3334,300,771,'5374','Facility',3,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3335) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3335,300,771,'5372','',4,'Y','XFACILITY','Facility','N',NULL,200,NULL,'G',NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END

IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3326) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3326,300,771,'5374','Status',5,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3327) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3327,300,771,'5372','',6,'Y',NULL,'ProgramStatus','N',NULL,200,NULL,'S',NULL,'csp_GetProgramStatus','globalCodeId','CodeName',NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END

IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3332) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3332,300,771,'5374','Primary Care Coordinator',7,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3333) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3333,300,771,'5372','',8,'Y',NULL,'PrimaryCareCoOrdinatorId','N',NULL,200,NULL,'S',NULL,'ssp_GetActiveStaff','StaffId','StaffName',NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3328) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3328,300,771,'5374','Requested Date',9,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3329) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3329,300,771,'5367','',10,'Y',NULL,'ProgramRequestedDate','N',NULL,50,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3330) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3330,300,771,'5374','Enrolled Date',11,'Y',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
IF NOT EXISTS (SELECT * FROM Formitems WHERE FormItemId = 3331) BEGIN SET IDENTITY_INSERT dbo.Formitems ON INSERT INTO Formitems (FormItemId, formsectionid, FormSectionGroupId, ItemType, ItemLabel, SortOrder, active, GlobalCodeCategory, ItemColumnName, ItemRequiresComment, ItemCommentColumnName, ItemWidth, MaximumLength, DropdownType, SharedTableName, StoredProcedureName, ValueField, TextField, MultilineEditFieldHeight, EachRadioButtonOnNewLine) VALUES(3331,300,771,'5367','',12,'Y',NULL,'ProgramEnrolledDate','N',NULL,50,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL) SET IDENTITY_INSERT dbo.Formitems OFF END
