//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectoryDomains
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveDirectoryDomains()
        {
            this.ActiveDirectoryStaff = new HashSet<ActiveDirectoryStaff>();
        }
    
        public int ActiveDirectoryDomainId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string DomainName { get; set; }
        public string ProxyAccount { get; set; }
        public string ProxyPassword { get; set; }
        public string SearchRoot { get; set; }
        public string UserAttributeFilter { get; set; }
        public string InitalUserAttributeFilter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveDirectoryStaff> ActiveDirectoryStaff { get; set; }
    }
}
