//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public int StaffId { get; set; }
        public string Subject { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public string Description { get; set; }
        public int ShowTimeAs { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string SpecificLocation { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> GroupServiceId { get; set; }
        public Nullable<int> AppointmentProcedureGroupId { get; set; }
        public string RecurringAppointment { get; set; }
        public string RecurringDescription { get; set; }
        public Nullable<int> RecurringAppointmentId { get; set; }
        public Nullable<int> RecurringServiceId { get; set; }
        public Nullable<int> RecurringGroupServiceId { get; set; }
        public Nullable<int> RecurringOccurrenceIndex { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CancelReason { get; set; }
        public Nullable<int> ExamRoom { get; set; }
        public string ClientWasPresent { get; set; }
        public string OtherPersonsPresent { get; set; }
        public Nullable<int> NumberofTimeRescheduled { get; set; }
        public System.Guid RowIdentifier { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Programs Programs { get; set; }
        public virtual Client Client { get; set; }
        public virtual Location Location { get; set; }
    }
}
