//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentVersion()
        {
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.DocumentPDFGenerationQueue = new HashSet<DocumentPDFGenerationQueue>();
            this.DocumentServiceNoteGoals = new HashSet<DocumentServiceNoteGoal>();
            this.DocumentServiceNoteObjectives = new HashSet<DocumentServiceNoteObjective>();
        }
    
        public int DocumentVersionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int DocumentId { get; set; }
        public int Version { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string DocumentChanges { get; set; }
        public string ReasonForChanges { get; set; }
        public Nullable<int> RevisionNumber { get; set; }
        public string RefreshView { get; set; }
        public string ReasonForNewVersion { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentPDFGenerationQueue> DocumentPDFGenerationQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentServiceNoteGoal> DocumentServiceNoteGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentServiceNoteObjective> DocumentServiceNoteObjectives { get; set; }
    }
}
