//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentVersions = new HashSet<DocumentVersion>();
        }
    
        public int DocumentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> GroupServiceId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> DocumentCodeId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> CurrentDocumentVersionId { get; set; }
        public string DocumentShared { get; set; }
        public string SignedByAuthor { get; set; }
        public string SignedByAll { get; set; }
        public string ToSign { get; set; }
        public Nullable<int> ProxyId { get; set; }
        public string UnderReview { get; set; }
        public Nullable<int> UnderReviewBy { get; set; }
        public string RequiresAuthorAttention { get; set; }
        public string InitializedXML { get; set; }
        public Nullable<int> BedAssignmentId { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> InProgressDocumentVersionId { get; set; }
        public Nullable<int> CurrentVersionStatus { get; set; }
        public Nullable<int> ClientLifeEventId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        public virtual DocumentVersion DocumentVersion { get; set; }
        public virtual DocumentVersion DocumentVersion1 { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual DocumentCode DocumentCode { get; set; }
        public virtual Document Documents1 { get; set; }
        public virtual Document Documents2 { get; set; }
        public virtual Client Client { get; set; }
    }
}
