//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIMaster
    {
        public int KPIMasterId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string KPIName { get; set; }
        public string KPIDescription { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CollectionPeriod { get; set; }
        public Nullable<int> RetentionPeriod { get; set; }
        public Nullable<int> CollectionMethod { get; set; }
        public string Active { get; set; }
        public string RawData { get; set; }
        public string RawDataTableName { get; set; }
        public string CollectionStoredProcedure { get; set; }
        public string ProcessingStoredProcedure { get; set; }
    }
}
