//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileOrigins
    {
        public int MobileOriginId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string OriginSecret { get; set; }
        public string Name { get; set; }
        public int ApplicationType { get; set; }
        public string Active { get; set; }
        public Nullable<int> RefreshTokenLifeTime { get; set; }
        public string AllowedOrigin { get; set; }
        public Nullable<int> RefreshTokenLifeTimeType { get; set; }
    }
}
