//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programs()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Services = new HashSet<Service>();
            this.Staff = new HashSet<Staff>();
        }
    
        public int ProgramId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramName { get; set; }
        public string Active { get; set; }
        public Nullable<int> ProgramType { get; set; }
        public string IntakePhone { get; set; }
        public string IntakePhoneText { get; set; }
        public Nullable<int> ProgramManager { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Comment { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string AddressDisplay { get; set; }
        public string NationalProviderId { get; set; }
        public string InpatientProgram { get; set; }
        public int ServiceAreaId { get; set; }
        public string CanNotBePrimaryAssignment { get; set; }
        public string CustomField { get; set; }
        public string ResidentialProgram { get; set; }
        public string AfterSchoolProgram { get; set; }
        public string ShowInWhiteBoard { get; set; }
        public Nullable<int> FacilityType { get; set; }
        public string AutomaticAttendanceForBedAssignment { get; set; }
        public string BedAdmissionRequiresOrder { get; set; }
        public string BedDischargeRequiresOrder { get; set; }
        public string PrimaryCareProgram { get; set; }
        public string UseProblemListForDiagnosis { get; set; }
        public string UseDiagnosisDocument { get; set; }
        public string DiagnosisDocumentCategoryAll { get; set; }
        public string MARClientOrderMedication { get; set; }
        public string MARPrescribedMedication { get; set; }
        public string MARNonOrderedMedication { get; set; }
        public Nullable<int> TreatmentPlanCatalogId { get; set; }
        public string Mobile { get; set; }
        public string CreateServiceForDischargeDate { get; set; }
        public string TaxId { get; set; }
        public string CQMCode { get; set; }
        public Nullable<int> CQMCodeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
