//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDiagnosi
    {
        public int ServiceDiagnosisId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string DSMCode { get; set; }
        public Nullable<int> DSMNumber { get; set; }
        public string DSMVCodeId { get; set; }
        public string ICD10Code { get; set; }
        public string ICD9Code { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
