//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Documents = new HashSet<Document>();
            this.ServiceDiagnosis = new HashSet<ServiceDiagnosi>();
        }
    
        public int ServiceId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> GroupServiceId { get; set; }
        public int ProcedureCodeId { get; set; }
        public System.DateTime DateOfService { get; set; }
        public Nullable<System.DateTime> EndDateOfService { get; set; }
        public string RecurringService { get; set; }
        public decimal Unit { get; set; }
        public Nullable<int> UnitType { get; set; }
        public int Status { get; set; }
        public Nullable<int> CancelReason { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> ClinicianId { get; set; }
        public Nullable<int> AttendingId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Billable { get; set; }
        public string ClientWasPresent { get; set; }
        public string OtherPersonsPresent { get; set; }
        public Nullable<int> AuthorizationsApproved { get; set; }
        public Nullable<int> AuthorizationsNeeded { get; set; }
        public Nullable<int> AuthorizationsRequested { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<int> NumberOfTimeRescheduled { get; set; }
        public Nullable<int> NumberOfTimesCancelled { get; set; }
        public Nullable<int> ProcedureRateId { get; set; }
        public string DoNotComplete { get; set; }
        public string Comment { get; set; }
        public string Flag1 { get; set; }
        public string OverrideError { get; set; }
        public string OverrideBy { get; set; }
        public Nullable<int> ReferringId { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public Nullable<int> NoteAuthorId { get; set; }
        public Nullable<int> ModifierId1 { get; set; }
        public Nullable<int> ModifierId2 { get; set; }
        public Nullable<int> ModifierId3 { get; set; }
        public Nullable<int> ModifierId4 { get; set; }
        public Nullable<int> PlaceOfServiceId { get; set; }
        public string SpecificLocation { get; set; }
        public string OverrideCharge { get; set; }
        public Nullable<decimal> OverrideChargeAmount { get; set; }
        public string ChargeAmountOverrideBy { get; set; }
        public string NoteReplacement { get; set; }
        public string AttachmentComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDiagnosi> ServiceDiagnosis { get; set; }
        public virtual Programs Programs { get; set; }
        public virtual ProcedureCodes ProcedureCodes { get; set; }
        public virtual Client Client { get; set; }
        public virtual Location Location { get; set; }
    }
}
