//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffPreferences
    {
        public int StaffPreferenceId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int StaffId { get; set; }
        public Nullable<int> DefaultMobileHomePageId { get; set; }
        public Nullable<int> DefaultMobileProgramId { get; set; }
        public Nullable<int> MobileCalendarEventsDaysLookUpInPast { get; set; }
        public Nullable<int> MobileCalendarEventsDaysLookUpInFuture { get; set; }
        public Nullable<int> TreatmentTeamRole { get; set; }
        public string StreamlineStaff { get; set; }
        public string NotifyMeOfMyServices { get; set; }
        public string RegisteredForMobileNotifications { get; set; }
        public Nullable<System.DateTime> LastTFATimeStamp { get; set; }
        public Nullable<System.DateTime> RegisteredForMobileNotificationsTimeStamp { get; set; }
        public string RegisteredForSMSNotifications { get; set; }
        public string RegisteredForEmailNotifications { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
