//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffClientAccess
    {
        public int StaffClientAccessId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public int StaffId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SystemScreenId { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string ActivityType { get; set; }
        public string TableName { get; set; }
        public string HashValues { get; set; }
    
        public virtual Client Clients { get; set; }
        public virtual Screens Screens { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
