//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Staff1 = new HashSet<Staff>();
            this.Staff11 = new HashSet<Staff>();
            this.Staff12 = new HashSet<Staff>();
            this.Appointments = new HashSet<Appointment>();
            this.Services = new HashSet<Service>();
            this.Services1 = new HashSet<Service>();
            this.Services2 = new HashSet<Service>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.Documents2 = new HashSet<Document>();
            this.DocumentVersions = new HashSet<DocumentVersion>();
            this.Programs1 = new HashSet<Programs>();
            this.MobileBriefcase = new HashSet<MobileBriefcase>();
            this.Clients = new HashSet<Client>();
            this.Clients1 = new HashSet<Client>();
            this.Clients2 = new HashSet<Client>();
            this.Clients3 = new HashSet<Client>();
            this.Clients4 = new HashSet<Client>();
            this.Clients5 = new HashSet<Client>();
            this.StaffClientAccess = new HashSet<StaffClientAccess>();
            this.MobileDevices = new HashSet<MobileDevice>();
            this.StaffPreferences = new HashSet<StaffPreferences>();
        }
    
        public int StaffId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowIdentifier { get; set; }
        public string RecordDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UserCode { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Active { get; set; }
        public string SSN { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> EmploymentStart { get; set; }
        public Nullable<System.DateTime> EmploymentEnd { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<int> TaxonomyCode { get; set; }
        public Nullable<int> Degree { get; set; }
        public string SigningSuffix { get; set; }
        public string CosignRequired { get; set; }
        public string Clinician { get; set; }
        public string Attending { get; set; }
        public string ProgramManager { get; set; }
        public string IntakeStaff { get; set; }
        public string AppointmentSearch { get; set; }
        public string CoSigner { get; set; }
        public string AdminStaff { get; set; }
        public string Prescriber { get; set; }
        public Nullable<int> LastSynchronizedId { get; set; }
        public string UserPassword { get; set; }
        public string AllowedPrinting { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string OfficePhone1 { get; set; }
        public string OfficePhone2 { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string PagerNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string AddressDisplay { get; set; }
        public string InLineSpellCheck { get; set; }
        public string DisplayPrimaryClients { get; set; }
        public string FontName { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<bool> SynchronizationOnStart { get; set; }
        public Nullable<bool> SynchronizationOnClose { get; set; }
        public string EncryptionSwitch { get; set; }
        public Nullable<int> PrimaryRoleId { get; set; }
        public Nullable<int> PrimaryProgramId { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> PasswordExpires { get; set; }
        public string PasswordExpiresNextLogin { get; set; }
        public Nullable<System.DateTime> PasswordExpirationDate { get; set; }
        public string SendConnectionInformation { get; set; }
        public string PasswordSendMethod { get; set; }
        public string PasswordCallPhoneNumber { get; set; }
        public string AccessCareManagement { get; set; }
        public string AccessSmartCare { get; set; }
        public string AccessPracticeManagement { get; set; }
        public string Administrator { get; set; }
        public string SystemAdministrator { get; set; }
        public string CanViewStaffProductivity { get; set; }
        public string CanCreateManageStaff { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ProductivityDashboardUnit { get; set; }
        public string ProductivityComment { get; set; }
        public string TargetsComment { get; set; }
        public string HomePage { get; set; }
        public Nullable<int> DefaultReceptionViewId { get; set; }
        public string DefaultCalenderViewType { get; set; }
        public Nullable<int> DefaultMultiStaffViewId { get; set; }
        public Nullable<int> DefaultProgramViewId { get; set; }
        public Nullable<int> DefaultCalendarIncrement { get; set; }
        public string UsePrimaryProgramForCaseload { get; set; }
        public string EHRUser { get; set; }
        public Nullable<int> DefaultReceptionStatus { get; set; }
        public string NationalProviderId { get; set; }
        public string ClientPagePreferences { get; set; }
        public Nullable<int> RetainMessagesDays { get; set; }
        public Nullable<int> MedicationDaysDefault { get; set; }
        public string ViewDocumentsBanner { get; set; }
        public string ExternalReferenceId { get; set; }
        public string DEANumber { get; set; }
        public string Supervisor { get; set; }
        public Nullable<int> DefaultPrescribingLocation { get; set; }
        public Nullable<int> DefaultImageServerId { get; set; }
        public Nullable<System.DateTime> LastPrescriptionReviewTime { get; set; }
        public Nullable<int> DefaultPrescribingQuantity { get; set; }
        public string AllowRemoteAccess { get; set; }
        public string CanSignUsingSignaturePad { get; set; }
        public string SureScriptsPrescriberId { get; set; }
        public string SureScriptsLocationId { get; set; }
        public Nullable<System.DateTime> SureScriptsActiveStartTime { get; set; }
        public Nullable<System.DateTime> SureScriptsActiveEndTime { get; set; }
        public Nullable<System.DateTime> SureScriptsLastUpdateTime { get; set; }
        public Nullable<int> SureScriptsServiceLevel { get; set; }
        public string AllowEmergencyAccess { get; set; }
        public Nullable<int> EmergencyAccessRoleId { get; set; }
        public Nullable<int> HomePageScreenId { get; set; }
        public Nullable<int> ClientPagePreferenceScreenId { get; set; }
        public string AuthenticationType { get; set; }
        public string AccessProviderAccess { get; set; }
        public Nullable<decimal> ProjectedTimeOffHours { get; set; }
        public string Initial { get; set; }
        public Nullable<int> RxAuthorizedProvider { get; set; }
        public Nullable<int> DetermineCaseloadBy { get; set; }
        public string Color { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string DisplayAs { get; set; }
        public string NonStaffUser { get; set; }
        public Nullable<int> TempClientId { get; set; }
        public Nullable<int> TempClientContactId { get; set; }
        public string DirectEmailAddress { get; set; }
        public string DirectEmailPassword { get; set; }
        public Nullable<int> DXSearchPreference { get; set; }
        public string AllInsurers { get; set; }
        public Nullable<int> PrimaryInsurerId { get; set; }
        public string AllProviders { get; set; }
        public Nullable<int> PrimaryProviderId { get; set; }
        public string All837Senders { get; set; }
        public Nullable<int> FinancialAssignmentId { get; set; }
        public string EnableRxPopupAcknowledgement { get; set; }
        public string MobileSmartKey { get; set; }
        public string AllowMobileAccess { get; set; }
        public string NADEANumber { get; set; }
        public string MobileSmartKeyExpiresNextLogin { get; set; }
        public string AllowAccessToAllScannedDocuments { get; set; }
        public string IsEPCSEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff11 { get; set; }
        public virtual Staff Staff3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff12 { get; set; }
        public virtual Staff Staff4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        public virtual Screens Screens { get; set; }
        public virtual Screens Screens1 { get; set; }
        public virtual Programs Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programs> Programs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileBriefcase> MobileBriefcase { get; set; }
        public virtual ActiveDirectoryStaff ActiveDirectoryStaff { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients4 { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffClientAccess> StaffClientAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDevice> MobileDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffPreferences> StaffPreferences { get; set; }
    }
}
