//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigurations
    {
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> ClientBannerDocument1 { get; set; }
        public Nullable<int> ClientBannerDocument2 { get; set; }
        public Nullable<int> ClientBannerDocument3 { get; set; }
        public Nullable<int> ClientBannerDocument4 { get; set; }
        public Nullable<int> ClientBannerDocument5 { get; set; }
        public Nullable<int> ClientBannerDocument6 { get; set; }
        public string StateFIPS { get; set; }
        public string LastUserName { get; set; }
        public Nullable<int> FiscalMonth { get; set; }
        public Nullable<double> DatabaseVersion { get; set; }
        public Nullable<double> CustomDatabaseVersion { get; set; }
        public Nullable<double> SmartCareVersionMinimum { get; set; }
        public Nullable<double> SmartCareVersionMaximum { get; set; }
        public Nullable<double> PracticeManagementVersionMinimum { get; set; }
        public Nullable<double> PracticeManagementVersionMaximum { get; set; }
        public Nullable<double> CareManagementVersionMinimum { get; set; }
        public Nullable<double> CareManagementVersionMaximum { get; set; }
        public Nullable<double> ProviderAccessVersionMinimum { get; set; }
        public Nullable<double> ProviderAccessVersionMaximum { get; set; }
        public string CareManagementServer { get; set; }
        public string CareManagementDatabase { get; set; }
        public string AutoCreateDiagnosisFromAssessment { get; set; }
        public Nullable<int> CareManagementInsurerId { get; set; }
        public string IntializeAssessmentDiagnosis { get; set; }
        public string CareManagementInsurerName { get; set; }
        public string CareManagementComment { get; set; }
        public Nullable<int> ClientStatementSort1 { get; set; }
        public Nullable<int> ClientStatementSort2 { get; set; }
        public string SCDefaultDoNotComplete { get; set; }
        public string PMDefaultDoNotComplete { get; set; }
        public Nullable<int> MedicationDaysDefault { get; set; }
        public Nullable<double> MedicationDatabaseVersion { get; set; }
        public Nullable<int> RecurringAppointmentsExpandedFromDays { get; set; }
        public Nullable<int> RecurringAppointmentsExpandedToDays { get; set; }
        public Nullable<System.DateTime> RecurringAppointmentsExpandedFrom { get; set; }
        public Nullable<System.DateTime> RecurringAppointmentsExpandedTo { get; set; }
        public string ProgramsBannerText { get; set; }
        public string ShowGroupsBanner { get; set; }
        public string ShowBedCensusBanner { get; set; }
        public string FilterTPAuthorizationCodesByAssigned { get; set; }
        public string ShowTPProceduresViewMode { get; set; }
        public string DisableNoShowNotes { get; set; }
        public string DisableCancelNotes { get; set; }
        public string DisableCancelEventNotes { get; set; }
        public Nullable<int> CredentialingExpirationMonths { get; set; }
        public Nullable<int> CredentialingApproachingExpirationDays { get; set; }
        public string ImageDatabaseConfigurationName { get; set; }
        public string MedicationPatientOverviewTemplate { get; set; }
        public Nullable<int> ScannedMedicalRecordAuthorId { get; set; }
        public Nullable<int> AssessmentBannerId { get; set; }
        public Nullable<int> TreatmentPlanBannerId { get; set; }
        public Nullable<int> PeriodicReviewBannerId { get; set; }
        public Nullable<int> GeneralDocumentsBannerId { get; set; }
        public Nullable<int> DiagnosisBannerId { get; set; }
        public Nullable<int> ServicesBannerId { get; set; }
        public Nullable<int> DocumentListPageDefaultDocumentBannerId { get; set; }
        public Nullable<int> MedicationRxEndDateOffset { get; set; }
        public Nullable<int> SystemDatabaseId { get; set; }
        public string EnablePrescriberSecurityQuestion { get; set; }
        public string ProxyVerificationMessage { get; set; }
        public Nullable<int> NumberOfSecurityQuestions { get; set; }
        public Nullable<int> NumberOfPrescriberSecurityQuestions { get; set; }
        public Nullable<int> PharmacyCoverLetters { get; set; }
        public string EnablePrescriptionReview { get; set; }
        public string VerbalOrdersRequireApproval { get; set; }
        public string AllowRePrintFax { get; set; }
        public string AllowAllergyMedications { get; set; }
        public Nullable<int> AutoSaveTimeDuration { get; set; }
        public string AutoSaveEnabled { get; set; }
        public string SureScriptsOrganizationId { get; set; }
        public Nullable<int> ConsentDurationMonths { get; set; }
        public string MedConsentsRequireClientSignature { get; set; }
        public string EnableOtherPrescriberSelection { get; set; }
        public Nullable<int> ReleaseListPageDefaultDocumentBannerId { get; set; }
        public Nullable<int> ListPageRowsPerPage { get; set; }
        public string MergeClientsProcess { get; set; }
        public Nullable<int> NumberOfDaysRecurringServicesSchedule { get; set; }
        public string ChangeOrderStartDateUseToday { get; set; }
        public Nullable<int> ShowNotificationPollingInterval { get; set; }
        public Nullable<int> InpatientAdmissionDocumentCodeId { get; set; }
        public Nullable<int> InpatientTransferDocumentCodeId { get; set; }
        public Nullable<int> InpatientDischargeDocumentCodeId { get; set; }
        public Nullable<int> InpatientOnLeaveDocumentCodeId { get; set; }
        public Nullable<int> EmergencyAccessMinutes { get; set; }
        public string DocumentsInProgressShowWatermark { get; set; }
        public string DocumentsInProgressWatermarkImageLocation { get; set; }
        public string AllowMessageToBePartOfClientRecord { get; set; }
        public string DefaultMessageToBePartOfClientRecord { get; set; }
        public Nullable<int> ClientEducationHealthDataMonths { get; set; }
        public Nullable<int> SystemConfigurations1 { get; set; }
        public Nullable<int> DisclosureCoverLetterReportFolderId { get; set; }
        public Nullable<int> DisclosureReportsFolderId { get; set; }
        public string AllowStaffAuthorizations { get; set; }
        public Nullable<int> FaxingInterface { get; set; }
        public string ServiceDetailsServicePagePath { get; set; }
        public string ServiceNoteServicePagePath { get; set; }
        public string ScreenCustomTabExceptions { get; set; }
        public string EnableADAuthentication { get; set; }
        public string UseKeyPhrases { get; set; }
        public string OnlyChargeClientsWithFeeArrangement { get; set; }
        public Nullable<int> DocumentLockCheckProcessFrequency { get; set; }
        public string DocumentsDefaultCurrentEffectiveDate { get; set; }
        public string RefillStartUseEndPlusOne { get; set; }
        public string HideCustomAuthorizationControls { get; set; }
        public string DocumentSignaturesNoPassword { get; set; }
        public string PopulationTracking { get; set; }
        public Nullable<int> FaxCoverLetterFolderId { get; set; }
        public string ShareDocumentOnSave { get; set; }
        public string LimitMyCaseLoadPrograms { get; set; }
        public string ReportURL { get; set; }
        public string ReportFolderName { get; set; }
        public string ReportServerDomain { get; set; }
        public string ReportServerUserName { get; set; }
        public string ReportServerPassword { get; set; }
        public string ReportServerConnection { get; set; }
        public string DiagnosisHideAxisIIISpecify { get; set; }
        public string DiagnosisAxisIVShowNone { get; set; }
        public string ShowTPGoalsOnServiceTab { get; set; }
        public string ServiceOutTimeNotRequiredOnSave { get; set; }
        public Nullable<int> ReleaseReminderDays { get; set; }
        public string ServiceNoteDoNotDefaultDate { get; set; }
        public string AdjudicateSpendDown { get; set; }
        public string ClaimPopulationDropdown { get; set; }
        public Nullable<int> AppointmentSearchResultDays { get; set; }
        public string AlwaysCreateClientChargeOnServiceCompletion { get; set; }
        public Nullable<int> C835PaymentSourceId { get; set; }
        public Nullable<int> C835PaymentLocationId { get; set; }
        public string ChargeAccountingPeriodByDateOfService { get; set; }
        public Nullable<int> AuthorizationDetailsReportFolderId { get; set; }
        public Nullable<int> DefaultAppointmentDurationWhenNotSpecified { get; set; }
        public string HelpURL { get; set; }
        public string FlowSheetSpecificToClient { get; set; }
        public string UseSignaturePad { get; set; }
        public Nullable<int> ScannedDocumentDefaultAssociation { get; set; }
        public Nullable<int> AllowedResourceCount { get; set; }
        public string UseResourceForService { get; set; }
        public string ServiceInTimeNotRequiredOnSave { get; set; }
        public Nullable<int> DeductiblesNeverMetMonthsFromToday { get; set; }
        public Nullable<double> DataModelVersion { get; set; }
        public string DisableAuditLog { get; set; }
    }
}
