//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigurationKey
    {
        public int SystemConfigurationKeyId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string RecordDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string AcceptedValues { get; set; }
        public string ShowKeyForViewingAndEditing { get; set; }
        public string Modules { get; set; }
        public string Screens { get; set; }
        public string Comments { get; set; }
        public string SourceTableName { get; set; }
        public string AllowEdit { get; set; }
    }
}
