//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streamline.UserBusinessServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STREAMLINE\\STREAMLINE;Initial Catalog=RiverwoodScrubbed20071003;User " +
            "ID=shc;Password=shc")]
        public string RiverwoodScrubbed20071003ConnectionString {
            get {
                return ((string)(this["RiverwoodScrubbed20071003ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STREAMLINE\\STREAMLINE;Initial Catalog=RiverwoodScrubbed_QA5.8;User ID" +
            "=shc;Password=shc")]
        public string RiverwoodScrubbedRemote4_7ConnectionString {
            get {
                return ((string)(this["RiverwoodScrubbedRemote4_7ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STREAMLINE\\STREAMLINE;Initial Catalog=RiverwoodScrubbed_QA6.9;User ID" +
            "=shc;Password=shc")]
        public string RiverwoodScrubbed_QA6_9ConnectionString {
            get {
                return ((string)(this["RiverwoodScrubbed_QA6_9ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Driver={SQL Server};description=test;server=STREAMLINE;uid=shc1979;pwd=shc1979;ap" +
            "p=Microsoft® Visual Studio® 2005;wsid=SDEI15;database=MedicationDev8.56")]
        public string MedicationDev8_56ConnectionString {
            get {
                return ((string)(this["MedicationDev8_56ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STREAMLINE;Initial Catalog=\"Medication Management8.6883_Dev\";User ID=" +
            "shc1979;Password=shc1979")]
        public string Medication_Management8_6883_DevConnectionString {
            get {
                return ((string)(this["Medication_Management8_6883_DevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ExterWebService/ExternalWebService.asmx")]
        public string Streamline_UserBusinessServices_ExternalWebService_ExternalWebService {
            get {
                return ((string)(this["Streamline_UserBusinessServices_ExternalWebService_ExternalWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STREAMLINE01;Initial Catalog=ReportServer_9.35_6.5_QA;User ID=shcdev;" +
            "Password=shcdev")]
        public string ReportServer_9_35_6_5_QAConnectionString {
            get {
                return ((string)(this["ReportServer_9_35_6_5_QAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB;Data Source=dev.smartcarenet.com;User ID=shstest;Initial Catalo" +
            "g=Kalamazoo_3_QA")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
