/***********************************************************
*Run After Creating the prerequisite Procs via DFACustomProcs.sql
*
*12/26/14 - TRyan - Created
***********************************************************/

BEGIN TRY 
BEGIN TRAN

DECLARE @FormId INT,
	@FormSectionId INT,
	@ForMSectionGroupId INT,
	@FormItemId INT

--Parent Table
EXEC csp_DFACreateForm 
	@FormName = 'CustomClients',
	@TableName = 'CustomClients',
	@TotalNumberOfColumns = 1,
	@Active = 'Y',
	@RetrieveStoredProcedure = NULL,
	@JavascriptFilePath = NULL,
	@FormId = @FormId OUTPUT
	--,@abortIfExists = 'N'

--Form Children
EXEC csp_DFACreateFormSection
	@FormId = @FormId,
	@SortOrder = 1,
	@PlaceOnTopOfPage = 'N',
	@SectionLabel = 'Child Accompaniment',
	@Active = 'Y',
	@SectionEnableCheckBox = 'Y',
	@SectionEnableCheckBoxText = 'Client is accompanied by child in residential care',
	@SectionEnableCheckBoxColumnName = 'AccompaniedByChild',
	@NumberOfColumns = 1,
	@ShowPencilIcon = NULL,
	@FormSectionId = @FormSectionId OUTPUT
	--,@abortIfExists = 'N'

--FormSectionChildren
EXEC csp_DFACreateFormSectionGroup
	@FormSectionId = @FormSectionId,
	@GroupName = NULL,
	@SortOrder = 1,
	@GroupLabel = NULL,
	@Active = 'Y',
	@GroupEnableCheckBox = 'N',
	@GroupEnableCheckBoxText = NULL,
	@GroupEnableCheckBoxColumnName = NULL,
	@NumberOfItemsInRow = 4,
	@ShowPencilIcon = NULL,
	@FormSectionGroupId = @FormSectionGroupId OUTPUT
	--,@abortIfExists = 'N'

--FromSectionGroup Children
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Child Name',
	@SortOrder = 1,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildName1',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 200,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'DOB',
	@SortOrder = 2,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildDOB1',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move In Date',
	@SortOrder = 3,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveInDate1',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move Out Date',
	@SortOrder = 4,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveOutDate1',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Reason for Leaving',
	@SortOrder = 5,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ReasonForLeaving1',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 163,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 6,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 7,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 8,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'

EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Child Name',
	@SortOrder = 9,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildName2',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 200,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'DOB',
	@SortOrder = 10,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildDOB2',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move In Date',
	@SortOrder = 11,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveInDate2',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move Out Date',
	@SortOrder = 12,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveOutDate2',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Reason for Leaving',
	@SortOrder = 13,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ReasonForLeaving2',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 163,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 14,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 15,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 16,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'

EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Child Name',
	@SortOrder = 17,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildName3',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 200,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'DOB',
	@SortOrder = 18,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ChildDOB3',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move In Date',
	@SortOrder = 19,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveInDate3',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Move Out Date',
	@SortOrder = 20,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'MoveOutDate3',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Reason for Leaving',
	@SortOrder = 21,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'ReasonForLeaving3',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 163,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 22,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
		
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 23,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 24,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
--Form Children
EXEC csp_DFACreateFormSection
	@FormId = @FormId,
	@SortOrder = 2,
	@PlaceOnTopOfPage = 'N',
	@SectionLabel = 'Additional Educational Training',
	@Active = 'Y',
	@SectionEnableCheckBox = 'Y',
	@SectionEnableCheckBoxText = 'Client is currently enrolled in Educational/Vocational Training?',
	@SectionEnableCheckBoxColumnName = 'CurrentlyEnrolledInEducation',
	@NumberOfColumns = 1,
	@ShowPencilIcon = NULL,
	@FormSectionId = @FormSectionId OUTPUT
	--,@abortIfExists = 'N'

--FormSectionChildren
EXEC csp_DFACreateFormSectionGroup
	@FormSectionId = @FormSectionId,
	@GroupName = NULL,
	@SortOrder = 1,
	@GroupLabel = NULL,
	@Active = 'Y',
	@GroupEnableCheckBox = 'N',
	@GroupEnableCheckBoxText = NULL,
	@GroupEnableCheckBoxColumnName = NULL,
	@NumberOfItemsInRow = 1,
	@ShowPencilIcon = NULL,
	@FormSectionGroupId = @FormSectionGroupId OUTPUT
	--,@abortIfExists = 'N'
	
--FromSectionGroup Children
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Name of School',
	@SortOrder = 1,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'NameOfSchool',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 450,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
--Form Children
EXEC csp_DFACreateFormSection
	@FormId = @FormId,
	@SortOrder = 3,
	@PlaceOnTopOfPage = 'N',
	@SectionLabel = 'TCU Test Scores',
	@Active = 'Y',
	@SectionEnableCheckBox = 'N',
	@SectionEnableCheckBoxText = NULL,
	@SectionEnableCheckBoxColumnName = NULL,
	@NumberOfColumns = 1,
	@ShowPencilIcon = NULL,
	@FormSectionId = @FormSectionId OUTPUT
	--,@abortIfExists = 'N'

--FormSectionChildren
EXEC csp_DFACreateFormSectionGroup
	@FormSectionId = @FormSectionId,
	@GroupName = NULL,
	@SortOrder = 1,
	@GroupLabel = NULL,
	@Active = 'Y',
	@GroupEnableCheckBox = 'N',
	@GroupEnableCheckBoxText = NULL,
	@GroupEnableCheckBoxColumnName = NULL,
	@NumberOfItemsInRow = 2,
	@ShowPencilIcon = NULL,
	@FormSectionGroupId = @FormSectionGroupId OUTPUT
	--,@abortIfExists = 'N'
	
--FromSectionGroup Children
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Entry Score Date',
	@SortOrder = 1,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'TCUEntryDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Score',
	@SortOrder = 2,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'TCUScore',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 250,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = '90 Day Score Date',
	@SortOrder = 3,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'NinetyDayScoreDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Score',
	@SortOrder = 4,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'NinetyDayScore',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 250,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Discharge Score Date',
	@SortOrder = 5,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'DischargeScoreDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5361,
	@ItemLabel = 'Score',
	@SortOrder = 6,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'DischargeScore',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 250,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'

--Form Children
EXEC csp_DFACreateFormSection
	@FormId = @FormId,
	@SortOrder = 4,
	@PlaceOnTopOfPage = 'N',
	@SectionLabel = 'AIP Information',
	@Active = 'Y',
	@SectionEnableCheckBox = 'N',
	@SectionEnableCheckBoxText = NULL,
	@SectionEnableCheckBoxColumnName = NULL,
	@NumberOfColumns = 1,
	@ShowPencilIcon = NULL,
	@FormSectionId = @FormSectionId OUTPUT
	--,@abortIfExists = 'N'

--FormSectionChildren
EXEC csp_DFACreateFormSectionGroup
	@FormSectionId = @FormSectionId,
	@GroupName = NULL,
	@SortOrder = 1,
	@GroupLabel = NULL,
	@Active = 'Y',
	@GroupEnableCheckBox = 'N',
	@GroupEnableCheckBoxText = NULL,
	@GroupEnableCheckBoxColumnName = NULL,
	@NumberOfItemsInRow = 3,
	@ShowPencilIcon = NULL,
	@FormSectionGroupId = @FormSectionGroupId OUTPUT
	--,@abortIfExists = 'N'
	
--FromSectionGroup Children
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Date of Incarceration',
	@SortOrder = 1,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'AIPDateOfIncarceration',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Potential Release Date',
	@SortOrder = 2,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'AIPPotentialReleaseDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Actual Release Date',
	@SortOrder = 3,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'AIPActualReleaseDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Potential Transleave Date',
	@SortOrder = 4,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'AIPTransLeaveDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5367,
	@ItemLabel = 'Post-Prison Supervision End Date',
	@SortOrder = 5,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= 'AIPPostPrisonSupervisionEndDate',
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'
	
EXEC csp_DFACreateFormItem
	@FormSectionId = @FormSectionId,
	@FormSectionGroupId = @FormSectionGroupId,
	@ItemType = 5374,
	@ItemLabel = '',
	@SortOrder = 6,
	@Active = 'Y',
	@GlobalCodeCategory	= NULL,
	@ItemColumnName	= NULL,
	@ItemRequiresComment = 'N',
	@ItemCommentColumnName = NULL,
	@ItemWidth = 50,
	@MaximumLength = NULL,
	@DropdownType = NULL,
	@SharedTableName = NULL,
	@StoredProcedureName = NULL,
	@ValueField = NULL,
	@TextField = NULL,
	@MultilineEditFieldHeight= NULL,
	@EachRadioButtonOnNewLine = 'N',
	@InformationIcon = 'N',
	@InformationIconStoredProcedure = NULL,
	@ExcludeFromPencilIcon = 'Y',
	@FormItemId = @FormItemId OUTPUT
	--,@abortIfExists = 'N'

COMMIT TRAN
END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0 ROLLBACK TRAN

DECLARE @errorMessage NVARCHAR(4000) 
SET @errorMessage = ERROR_MESSAGE()

RAISERROR(@errorMessage, 16, 1)

END CATCH