/****** Object:  StoredProcedure [dbo].[csp_SCWebGetCustomAcuteServicesPrescreens]    ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[csp_SCWebGetCustomAcuteServicesPrescreens]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[csp_SCWebGetCustomAcuteServicesPrescreens]
GO

/****** Object:  StoredProcedure [dbo].[csp_SCWebGetCustomAcuteServicesPrescreens]    ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 
                                                       
Create PROCEDURE [dbo].[csp_SCWebGetCustomAcuteServicesPrescreens]                                                                                         
(                          
  --@DocumentID int,                                                                                                                                      
  @DocumentVersionId int                                                                     
)                                                                                                
                                                                                                
AS                                                                                      
/***************************************************************************/                                                                                             
/* Stored Procedure: [csp_SCWebGetCustomAcuteServicesPrescreens] */                                                                                                                                             
/* Creation Date:  26-Feb-2010                */                                                                                                                                                      
/* Purpose: Gets Data [csp_SCWebGetCustomAcuteServicesPrescreens] */                                                                                                                                                     
/* Input Parameters: @DocumentId,@DocumentVersionId          */                                                                                                                                                    
/* Output Parameters:                   */                                                                                                                                                      
/* Return:  0=success, otherwise an error number                           */      
/* Change log:																*/
/* 2015.06.09 - T.Remisoski - added RiskSelfViolenceAbuse to match data model. */                                                                                 
                                                                                                
/***************************************************************************/                                                                                                
                                                                                      
BEGIN                                                                                                               
                                                                     
 BEGIN TRY                                                                                      
                            
      --------CustomAcuteServicesPrescreens-------------                                                         

	SELECT [DocumentVersionId]
,[CreatedBy]
,[CreatedDate]
,[ModifiedBy]
,[ModifiedDate]
,[RecordDeleted]
,[DeletedDate]
,[DeletedBy]
,[DateOfPrescreen]
,[InitialCallTime]
,[ClientAvailableTimeForScreen]
,[DispositionTime]
,[ElapsedHours]
,[ElapsedMinutes]
,[CMHStatus]
,[CMHStatusPrimaryClinician]
,[CMHCaseNumber]
,[ClientName]
,[ClientEthnicity]
,[ClientSex]
,[ClientMaritalStatus]
,[ClientSSN]
,[ClientDateOfBirth]
,[ClientAddress]
,[ClientCity]
,[ClientState]
,[ClientZip]
,[ClientCounty]
,[ClientHomePhone]
,[ClientEmergencyContact]
,[ClientRelationship]
,[ClientEmergencyPhone]
,[ClientGuardianName]
,[ClientGuardianPhone]
,[PaymentSourceIndigent]
,[PaymentSourcePrivate]
,[PaymentSourcePrivateEmployer]
,[PaymentSourcePrivateNumber]
,[PaymentSourceMedicare]
,[PaymentSourceMedicareNumber]
,[PaymentSourceMedicaid]
,[PaymentSourceMedicaidNumber]
,[PaymentSourceMedicaidType]
,[PaymentMedicaidOtherCounty]
,[PaymentSourceVA]
,[PaymentSourceOther]
,[PaymentSourceOtherDescribe]
,[PaymentMedicaidVerified]
,[ServiceRequested]
,[ClientRecentLocation]
,[ClientBelongingsLocation]
,[ClientMailLocation]
,[ClientReturnLocation]
,[ClientFromDifferentCounty]
,[ClientPriorLivingArrangement]
,[ClientIsWardofState]
,[ClientIsWardofStateCountyDetail]
,[COFRAdditionalInformation]
,[COFROtherCountyDetail]
,[ReferralSourceName]
,[ReferralSourcePhoneLocation]
,[ReferralSourceContacted]
,[ReferralSourceContactedExplain]
,[ReferralSourceJailLiason]
,[ReferralSourceFamilyMember]
,[ReferralSourcePhysician]
,[ReferralSourceMHProvider]
,[ReferralSourcePetitioned]
,[ReferralSourceOther]
,[ReferralSourceOtherSpecify]
,[ReferralContactTypeFaceToFace]
,[ReferralContactTypePhone]
,[ReferralContactTypePreBooking]
,[ReferralContactTypePostBooking]
,[ReferralPrecipitatingEvents]
,[RiskOthersAAgressiveWithin24Hours]
,[RiskOthersAgressivePast48Hours]
,[RiskOthersAgressiveWithinPast4Weeks]
,[RiskOthersCurrentHomicidalIdeation]
,[RiskOthersCurrentHomicidalActive]
,[RiskOthersCurrentHomicidalWithin48Hours]
,[RiskOthersCurrentHomicidalWithin14Days]
,[RiskOthersAWOL]
,[RiskOthersVerbal]
,[RiskOthersPhysical]
,[RiskOthersSexualActingOut]
,[RiskOthersDestructionOfProperty]
,[RiskOthersDestructionOfPropertyDescribe]
,[RiskOthersHasPlan]
,[RiskOthersHasPlanDescribe]
,[RiskOthersAccessToMeans]
,[RiskOthersAccessToMeansDescribe]
,[RiskOthersVerbalDescribe]
,[RiskOthersPhysicalDescribe]
,[RiskOthersSexualActingOutDescribe]
,[RiskOthersHistory]
,[RiskOthersChargesPending]
,[RiskOthersChargesPendingDescribe]
,[RiskOthersJailHold]
,[RiskSelfCurrentSuicidalIdeation]
,[RiskSelfCurrentSuicidalActive]
,[RiskSelfCurrentSuicidalWithin48Hours]
,[RiskSelfCurrentSuicidalWithin14Days]
,[RiskSelfHasPlan]
,[RiskSelfHasPlanDescribe]
,[RiskSelfEgoSyntonic]
,[RiskSelfEgoDystonic]
,[RiskSelfEgoDescribe]
,[RiskSelfAccessToMeans]
,[RiskSelfAccessToMeansDescribe]
,[RiskSelfCurrentSelfHarm]
,[RiskSelfCurrentSelfHarmDescribe]
,[RiskSelfCurrentSelfHarmOutcome]
,[RiskSelfPreviousSelfHarm]
,[RiskSelfPreviousSelfHarmDescribe]
,[RiskSelfPreviousSelfHarmOutcomes]
,[RiskSelfFamilySuicideHistory]
,[RiskSelfViolenceAbuse]
,[MentalStatusOrientaionPerson]
,[MentalStatusOrientaionPlace]
,[MentalStatusOrientaionTime]
,[MentalStatusOrientaionCircumstance]
,[MentalStatusLOCAlert]
,[MentalStatusLOCSedate]
,[MentalStatusLOCLethargic]
,[MentalStatusLOCObtunded]
,[MentalStatusLOCOther]
,[MentalStatusLOCOtherDescribe]
,[MentaStatusMoodAppropriate]
,[MentaStatusMoodIncongruent]
,[MentaStatusMoodHostile]
,[MentaStatusMoodTearful]
,[MentaStatusMoodOther]
,[MentaStatusMoodOtherDescribe]
,[MentaStatusAffectRestricted]
,[MentaStatusAffectUnremarkable]
,[MentaStatusAffectExpansive]
,[MentaStatusAffectOther]
,[MentaStatusAffectOtherDescribe]
,[MentaStatusThoughtLucid]
,[MentaStatusThoughtSuspicious]
,[MentaStatusThoughtObsessive]
,[MentaStatusThoughtObsessiveAbout]
,[MentaStatusThoughtTangential]
,[MentaStatusThoughtLoose]
,[MentaStatusThoughtDelusional]
,[MentaStatusThoughtPsychosis]
,[MentaStatusThoughtImpoverished]
,[MentaStatusThoughtConfused]
,[MentaStatusSpeechClear]
,[MentaStatusSpeechRapid]
,[MentaStatusSpeechSlurred]
,[MentaStatusJudgementImpaired]
,[MentaStatusJudgementImpairedDescribe]
,[MentalStatusImpulsivityApparent]
,[MentalStatusImpulsivityApparentDescribe]
,[MentalStatusInsightLimited]
,[MentalStatusInsightLimitedDescribe]
,[MentalStatusPxWithGrooming]
,[MentalStatusSleepDisturbance]
,[MentalStatusSleepDisturbanceDescribe]
,[MentalStatusEatingDisturbance]
,[MentalStatusEatingDisturbanceLbs]
,[MentalStatusNotMedicationComplaint]
,[SUCurrentUse]
,[SUOdorOfSubstance]
,[SUSlurredSpeech]
,[SUWithdrawalSymptoms]
,[SUDTOther]
,[SUOtherDescribe]
,[SUBlackOuts]
,[SURelatedArrests]
,[SURelatedSocialProblems]
,[SUFrequentAbsences]
,[SUCurrentTreatment]
,[SUCurrentTreatmentProvider]
,[SUProviderContactNumber]
,[SUHistory]
,[SUHistorySpecify]
,[SUPreviousTreatment]
,[SUReferralToSA]
,[SUWhereReferred]
,[SUNotReferredBecause]
,[SUToxicologyResults]
,[HHMentalHealthUnableToObtain]
,[HHNumberOfIPPsychHospitalizations]
,[HHMostRecentIPHospitalizationDate]
,[HHMostRecentIPHospitalizationFacility]
,[HHPreviousOPPsychTreatment]
,[HHOPPsychUnableToObtain]
,[HHTypeOfService]
,[HHCurrentProviderAndCredentials]
,[HHProviderCredentialsUnableToObtain]
,[HHDateLastSeenByCurrentProvider]
,[HHPrimaryCareProvider]
,[HHPrimaryCareProviderPhone]
,[HHNoPrimaryCarePhysician]
,[HHAllergies]
,[HHCurrentHealthConcerns]
,[HHPreviousHealthConcerns]
,[SIPsychiatricSymptoms]
,[SIPossibleHarmToSelf]
,[SIPossibleHarmToOthers]
,[SIMedicationDrugComplications]
,[SIDisruptionOfSelfCareAbilities]
,[SIImpairedPersonalAdjustment]
,[SIIntensityOfService]
,[SummaryVoluntary]
,[SummaryInvoluntary]
,[SummaryInpatientFacilityName]
,[AuthorizedDays]
,[SummaryCrisisResidential]
,[SummaryCrisisFacilityName]
,[SummaryPartialHospitalization]
,[SummaryPartialFacilityName]
,[SummaryACT]
,[SummaryCaseManagement]
,[SummaryIOP]
,[SummaryOutpatient]
,[SummarySubstanceAbuse]
,[SummaryOther]
,[SummaryOtherSpecify]
,[SummaryProviderRecommended]
,[SummaryFamilyNotificationOffered]
,[SummaryFamilyMemberName]
,[SummaryInpatientRequestedAndDenied]
,[SummarySecondOpinionRights]
,[SummaryOfferedAlternativeServices]
,[SummaryAlternativeServicesSpecify]
,[SummaryAgreedToAlternativeServices]
,[SummaryAlternativeAppointmentTime]
,[SummaryAlternativeAgencyName]
,[SummaryAlternativeAgencyContactNumber]
,[SummaryChooseOtherPlan]
,[SummaryChooseOtherPlanSpecify]
,[SummaryMedicaidRights]
,[SummaryMedicaidRightsWhyNot]
,[SummaryRefusedTreatment]
,[SummaryNoServicesNeeded]
,[SummaryUnableToObtainSignature]
,[SummaryUnableToObtainSignatureReason]
,[ClientSignedPaperCopy]
,[SummarySummary]
,[RiskSuicideHomicidePlanDetails]
,[RiskSuicideHomicidePlanAvailability]
,[RiskSuicideHomicidePlanTime]
,[RiskSuicideHomicidePlanLethalityMethod]
,[RiskSuicideHomisideAttempts]
,[RiskSuicideHomisideIsolation]
,[RiskSuicideHomisideProbabilityTiming]
,[RiskSuicideHomisidePrecaution]
,[RiskSuicideHomisideActingToGetHelp]
,[RiskSuicideHomisideFinalAct]
,[RiskSuicideHomisideActiveForAttempt]
,[RiskSuicideHomisideSucideNote]
,[RiskSuicideHomisideOvertCommunication]
,[RiskSuicideHomisideAllegedPurposed]
,[RiskSuicideHomisideExpectationFatality]
,[RiskSuicideHomisideConceptionOfMethod]
,[RiskSuicideHomisideSeriousnessOfAttempt]
,[RiskSuicideHomisideAttitudeLivingDying]
,[RiskSuicideHomisideMedicalStatus]
,[RiskSuicideHomisideConceptMedicalRescue]
,[RiskSuicideHomisideDegreePremeditation]
,[RiskSuicideHomisideStress]
,[RiskSuicideHomisideCopingBehavior]
,[RiskSuicideHomisideDepression]
,[RiskSuicideHomisideResource]
,[RiskSuicideHomisideLifeStyle]
,[RiskSuicideHomisideTotalScore]
,[RiskSuicideHomisideComments]
,[Recommendations]
,[RiskActionTakenMedicalER]
,[RiskActionTakenPsychiatricPlacement]
,[RiskActionTakenPsychiatricPlacementVoluntary]
,[RiskActionTakenPsychiatricPlacementInVoluntary]
,[ActionTakenPsychiatricPlacementHospital]
,[RiskActionDirectorsHoldPlaced]
,[RiskActionSecureTransport]
,[RiskActionSecureTransportCompanyName]
,[RiskActionTakenCrisisRespiteBed]
,[RiskActionTakenCrisisRespiteBedWithPsych]
,[RiskActionTakenCrisisRespiteBedWithoutPsych]
,[RiskActionTakenJail]
,[RiskActionSocialDextorBed]
,[RiskSentHomeAlone]
,[RiskSentHomeWithRelative]
,[RiskRefferedToFollowNextDay]
,[RiskReferedToPrivateProvider]
,[RiskReferedToPrivateProviderName]
,[RiskRefferedPyschiatristPMNHP]
,[RiskReferedToOther]
,[RiskReferedToOtherSpecify]
,[RiskSuicidePresentingDangersSuicide]
,[RiskSuicidePresentingDangersOtherHarmToSelf]
,[RiskSuicidePresentingDangersHarmToOthers]
,[RiskSuicidePresentingDangersHarmToProperty]
,[RowIdentifier]
		
                                   
  FROM [CustomAcuteServicesPrescreens]                         
  WHERE ISNull(RecordDeleted,'N')='N' AND DocumentVersionId=@DocumentVersionId                                                  
                                                                                      
    -----For CustomMedicationHistory Table                                                   
    --SELECT [MedicationHistoryId]                                            
    --  ,[DocumentVersionId]                                            
    --  ,[MedicationName]                                            
    --  ,[DosageFrequency]                                            
    --  ,[Purpose]                                            
    --  ,[PrescribingPhysician]                                            
    --  ,[RowIdentifier]                                            
    --  ,[CreatedBy]                                   
    --  ,[CreatedDate]                                            
    --  ,[ModifiedBy]                                            
    --  ,[ModifiedDate]                                            
    --  ,[RecordDeleted]                                            
    --  ,[DeletedDate]                                            
    --  ,[DeletedBy]                                                
    -- FROM CustomMedicationHistory where ISNull(RecordDeleted,'N')='N' AND DocumentVersionId=@DocumentVersionId                                                
                                         
--      ----For CustomSUSubstances Table                                                
     SELECT [SUSubstanceId]                                                
      ,[DocumentVersionId]                                                
      ,[SubstanceName]                                                
      ,[Amount]                                                
      ,[Frequency]                                                
      ,[RowIdentifier]                                                
      ,[CreatedBy]                                                
      ,[CreatedDate]                                                
      ,[ModifiedBy]                                                
      ,[ModifiedDate]                                                
      ,[RecordDeleted]                                                
      ,[DeletedDate]                                           
      ,[DeletedBy]                                                
      FROM CustomSUSubstances  where ISNull(RecordDeleted,'N')='N' AND DocumentVersionId=@DocumentVersionId                                                  
               
      --Diagnosis
		exec ssp_SCGetDataDiagnosisNew  @DocumentVersionId                         
                        
   END TRY                                                       
                                                                                       
                                                                                     
 BEGIN CATCH                                               
  DECLARE @Error varchar(8000)                                                                                                         
   SET @Error= Convert(varchar,ERROR_NUMBER()) + '*****' + Convert(varchar(4000),ERROR_MESSAGE())                                                                                                                                       
   + '*****' + isnull(Convert(varchar,ERROR_PROCEDURE()),'ssp_SCGetWebCustomAcuteServicesPrescreens')                                                 
   + '*****' + Convert(varchar,ERROR_LINE()) + '*****' + Convert(varchar,ERROR_SEVERITY())                                               
   + '*****' + Convert(varchar,ERROR_STATE())                                                                    
                                                                                                                                                      
                                                           
   RAISERROR                                                                                                                                       
   (                                                                                                              
    @Error, -- Message text.                                                                                                                                      
    16, -- Severity.      
    1 -- State.                                                                                                                                      
   );                                                                            
                                                            
 END CATCH                                                                                                  
END 



 
GO


