IF NOT EXISTS (SELECT * FROM dbo.GlobalCodeCategories WHERE Category = 'XLIVINGARRANGEMENT') 
	BEGIN INSERT INTO dbo.GlobalCodeCategories ( Category, CategoryName, Active, AllowAddDelete, AllowCodeNameEdit, AllowSortOrderEdit, Description, UserDefinedCategory, HasSubcodes, UsedInPracticeManagement, UsedInCareManagement) 
	VALUES('XLIVINGARRANGEMENT','XLIVINGARRANGEMENT','Y','Y','Y','Y',NULL,'N','N','N','N') END 

IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'On Street/Homeless Shelter') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','On Street/Homeless Shelter',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='On Street/Homeless Shelter',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'On Street/Homeless Shelter' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Private Residence-Independent') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','Private Residence-Independent',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='Private Residence-Independent',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Private Residence-Independent' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Private Residence-Dependent') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','Private Residence-Dependent',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='Private Residence-Dependent',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Private Residence-Dependent' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Jail/Correctional Facility Institutional Setting (NH, IMD, Psych, IP, VA, State Hospital)') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','Jail/Correctional Facility Institutional Setting (NH, IMD, Psych, IP, VA, State Hospital)',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='Jail/Correctional Facility Institutional Setting (NH, IMD, Psych, IP, VA, State Hospital)',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Jail/Correctional Facility Institutional Setting (NH, IMD, Psych, IP, VA, State Hospital)' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= '24 Hour Residential Care') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','24 Hour Residential Care',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='24 Hour Residential Care',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= '24 Hour Residential Care' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Adult/Child Foster Home') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','Adult/Child Foster Home',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='Adult/Child Foster Home',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Adult/Child Foster Home' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Unknown') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XLIVINGARRANGEMENT','Unknown',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XLIVINGARRANGEMENT',CodeName='Unknown',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XLIVINGARRANGEMENT' and CodeName= 'Unknown' END 