---INSERT SCRIPT FOR CAREPLANDOMAINS AS PER ASSESSMENT REQUIRMENT
---CREATED BY VEENA S MANI ON 29/01/2015

DELETE FROM CarePlanObjectives
DELETE FROM CarePlanGoals
DELETE FROM CarePlanNeeds
DELETE FROM CarePlanDomainObjectives
DELETE FROM CarePlanDomainGoals
DELETE FROM CarePlanDomainNeeds
DELETE FROM CarePlanDomains
------------CarePlanDomains-------------------------
SET IDENTITY_INSERT CarePlanDomains ON 
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(1,'Mental Health')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(2,'Substance Use')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(3,'Physical Health')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(4,'Social/Interpersonal')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(5,'Traumatic Events')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(6,'Housing')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(7,'Medication')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(8,'Daily Living')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(9,'Advance Directive')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(10,'Risk Behaviors')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(11,'Employment/Training')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(12,'Education')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(13,'ASAM')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(14,'Developmental')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(15,'Family/Parenting')
INSERT INTO [CarePlanDomains] ([CarePlanDomainId],[DomainName])VALUES(16,'Financial')
SET IDENTITY_INSERT CarePlanDomains OFF


----------------------CarePlanDomainNeeds-------------------------------
SET IDENTITY_INSERT CarePlanDomainNeeds ON
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(1,1,'MH History')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(2,2,'Substance Use')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(3,3,'Physical Health')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(4,4,'Cultural/Ethnic')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(5,5,'Abuse/Neglect/Trauma')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(6,4,'Sexual Behaviors')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(7,7,'Medication')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(8,3,'Immunity')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(9,15,'Family Functioning')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(10,4,'Sexual Preference/Orientation')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(11,11,'Education/Training')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(12,11,'Personal Career Planning')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(13,11,'Employment Opportunities')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(14,11,'Support Employment and Work Practices')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(15,11,'Work History')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(41,11,'Gainful Employment')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(42,12,'Education Challenges/Barriers')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(43,3,'Communicable Disease Risk')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(16,1,'Anxiety')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(17,1,'Depression')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(18,14,'Language')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(19,14,'Visual')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(20,14,'Intellectual')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(21,14,'Learning')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(22,14,'Prenatal Care')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(23,14,'Pregnancy')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(24,14,'Prenatal Exposures')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(25,14,'Medication during Pregnancy')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(26,14,'Issue with delivery')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(27,14,'Milestones')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(28,14,'Talk before walk')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(29,8,'General Appearance')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(30,14,'Intellectual Assessment')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(31,1,'Communication')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(32,1,'Mood')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(33,1,'Affect')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(34,1,'Speech')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(35,1,'Thought')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(36,1,'Behavior')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(37,1,'Orientation')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(38,1,'Insight')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(39,1,'Memory')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(40,1,'Reality Orientation')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(44,10,'Sucidiality')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(45,10,'Physical Aggression')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(46,10,'Other Risk Factor')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(47,9,'Advance Directive')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(48,12,'School/Work Role Performance')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(49,15,'Home Role Performance')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(50,4,'Community Role Performance')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(51,4,'Behavior Toward Others')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(52,1,'Moods/Emotions')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(53,10,'Self-Harmful Behavior')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(54,1,'Thinking')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(55,15,'Primary Material')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(56,15,'Primary Support')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(57,15,'Non-Custodial Material')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(58,15,'Non-Custodial Support')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(59,15,'Surrogate Material')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(60,15,'Surrogate Support')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(61,8,'Health Practices')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(62,6,'Housing Stability Maintenance')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(63,8,'Communication')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(64,10,'Safety')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(65,8,'Managing Time')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(66,16,'Managing Money')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(67,8,'Nutrition')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(68,8,'Problem Solving')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(69,15,'Family Relationships')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(70,2,'Alcohol/Drug Use')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(71,8,'Leisure')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(72,4,'Community Resources')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(73,4,'Social Network')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(74,4,'Sexuality')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(75,8,'Productivity')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(76,8,'Coping Skills')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(77,4,'Behavior Norms')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(78,8,'Personal Hygiene')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(79,8,'Grooming')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(80,8,'Dress')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(81,13,'Dimension 1')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(82,13,'Dimension 2')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(83,13,'Dimension 3')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(84,13,'Dimension 4')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(85,13,'Dimension 5')
INSERT INTO [CarePlanDomainNeeds] ([CarePlanDomainNeedId],[CarePlanDomainId],[NeedName])VALUES(86,13,'Dimension 6')

SET IDENTITY_INSERT CarePlanDomainNeeds OFF



