IF NOT EXISTS (SELECT * FROM dbo.GlobalCodeCategories WHERE Category = 'XEMPLOYMENTSTATUS') 
	BEGIN INSERT INTO dbo.GlobalCodeCategories ( Category, CategoryName, Active, AllowAddDelete, AllowCodeNameEdit, AllowSortOrderEdit, Description, UserDefinedCategory, HasSubcodes, UsedInPracticeManagement, UsedInCareManagement) 
	VALUES('XEMPLOYMENTSTATUS','XEMPLOYMENTSTATUS','Y','Y','Y','Y',NULL,'N','N','N','N') END 

IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Employed Full Time (35 Hrs or More)') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Employed Full Time (35 Hrs or More)',NULL,'Y','N',0,'1') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Employed Full Time (35 Hrs or More)',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='1' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Employed Full Time (35 Hrs or More)' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Employed Part Time (less than 35 Hrs)') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Employed Part Time (less than 35 Hrs)',NULL,'Y','N',0,'2') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Employed Part Time (less than 35 Hrs)',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='2' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Employed Part Time (less than 35 Hrs)' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Supported/Trans Employment') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Supported/Trans Employment',NULL,'Y','N',0,'13') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Supported/Trans Employment',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='13' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Supported/Trans Employment' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Homemaker') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Homemaker',NULL,'Y','N',0,'11') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Homemaker',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='11' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Homemaker' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Student') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Student',NULL,'Y','N',0,'15') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Student',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='15' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Student' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Retired') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Retired',NULL,'Y','N',0,'14') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Retired',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='14' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Retired' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unemployed, seeking work') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Unemployed, seeking work',NULL,'Y','N',0,'7') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Unemployed, seeking work',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='7' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unemployed, seeking work' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unemployed, NOT seeking work') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Unemployed, NOT seeking work',NULL,'Y','N',0,'12') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Unemployed, NOT seeking work',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='12' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unemployed, NOT seeking work' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Disabled - Not in Labor Force') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Disabled - Not in Labor Force',NULL,'Y','N',0,'3') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Disabled - Not in Labor Force',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='3' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Disabled - Not in Labor Force' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Ages 0-5') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder,ExternalCode1) values('XEMPLOYMENTSTATUS','Ages 0-5',NULL,'Y','N',0,'10') END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Ages 0-5',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1='10' WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Ages 0-5' END 
IF NOT EXISTS (SELECT * FROM globalcodes WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unknown') begin INSERT INTO globalcodes ( Category, CodeName, Description, Active, CannotModifyNameOrDelete, SortOrder) values('XEMPLOYMENTSTATUS','Unknown',NULL,'Y','N',0) END ELSE BEGIN UPDATE globalcodes  set Category='XEMPLOYMENTSTATUS',CodeName='Unknown',Description=NULL,Active='Y',CannotModifyNameOrDelete='N',SortOrder=0, ExternalCode1=NULL WHERE Category = 'XEMPLOYMENTSTATUS' and CodeName= 'Unknown' END 