//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Streamline.UserBusinessServices.ExternalWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExternalWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ExternalWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloChandanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientSearchInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExternalClientInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateClientExternalViewAuditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExternalWebService() {
            this.Url = "http://localhost/ExterWebService/ExternalWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event HelloChandanCompletedEventHandler HelloChandanCompleted;
        
        /// <remarks/>
        public event GetClientInfoCompletedEventHandler GetClientInfoCompleted;
        
        /// <remarks/>
        public event GetClientSearchInfoCompletedEventHandler GetClientSearchInfoCompleted;
        
        /// <remarks/>
        public event GetExternalClientInfoCompletedEventHandler GetExternalClientInfoCompleted;
        
        /// <remarks/>
        public event UpdateClientExternalViewAuditCompletedEventHandler UpdateClientExternalViewAuditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloChandan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloChandan() {
            object[] results = this.Invoke("HelloChandan", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloChandanAsync() {
            this.HelloChandanAsync(null);
        }
        
        /// <remarks/>
        public void HelloChandanAsync(object userState) {
            if ((this.HelloChandanOperationCompleted == null)) {
                this.HelloChandanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloChandanOperationCompleted);
            }
            this.InvokeAsync("HelloChandan", new object[0], this.HelloChandanOperationCompleted, userState);
        }
        
        private void OnHelloChandanOperationCompleted(object arg) {
            if ((this.HelloChandanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloChandanCompleted(this, new HelloChandanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetClientInfo(int ClientId) {
            object[] results = this.Invoke("GetClientInfo", new object[] {
                        ClientId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientInfoAsync(int ClientId) {
            this.GetClientInfoAsync(ClientId, null);
        }
        
        /// <remarks/>
        public void GetClientInfoAsync(int ClientId, object userState) {
            if ((this.GetClientInfoOperationCompleted == null)) {
                this.GetClientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientInfoOperationCompleted);
            }
            this.InvokeAsync("GetClientInfo", new object[] {
                        ClientId}, this.GetClientInfoOperationCompleted, userState);
        }
        
        private void OnGetClientInfoOperationCompleted(object arg) {
            if ((this.GetClientInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientInfoCompleted(this, new GetClientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientSearchInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetClientSearchInfo(int UserId, string SearchType, string param1, string param2, string CreatedBy, int ProviderId) {
            object[] results = this.Invoke("GetClientSearchInfo", new object[] {
                        UserId,
                        SearchType,
                        param1,
                        param2,
                        CreatedBy,
                        ProviderId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientSearchInfoAsync(int UserId, string SearchType, string param1, string param2, string CreatedBy, int ProviderId) {
            this.GetClientSearchInfoAsync(UserId, SearchType, param1, param2, CreatedBy, ProviderId, null);
        }
        
        /// <remarks/>
        public void GetClientSearchInfoAsync(int UserId, string SearchType, string param1, string param2, string CreatedBy, int ProviderId, object userState) {
            if ((this.GetClientSearchInfoOperationCompleted == null)) {
                this.GetClientSearchInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientSearchInfoOperationCompleted);
            }
            this.InvokeAsync("GetClientSearchInfo", new object[] {
                        UserId,
                        SearchType,
                        param1,
                        param2,
                        CreatedBy,
                        ProviderId}, this.GetClientSearchInfoOperationCompleted, userState);
        }
        
        private void OnGetClientSearchInfoOperationCompleted(object arg) {
            if ((this.GetClientSearchInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientSearchInfoCompleted(this, new GetClientSearchInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExternalClientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetExternalClientInfo(string ExternalClientId) {
            object[] results = this.Invoke("GetExternalClientInfo", new object[] {
                        ExternalClientId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetExternalClientInfoAsync(string ExternalClientId) {
            this.GetExternalClientInfoAsync(ExternalClientId, null);
        }
        
        /// <remarks/>
        public void GetExternalClientInfoAsync(string ExternalClientId, object userState) {
            if ((this.GetExternalClientInfoOperationCompleted == null)) {
                this.GetExternalClientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExternalClientInfoOperationCompleted);
            }
            this.InvokeAsync("GetExternalClientInfo", new object[] {
                        ExternalClientId}, this.GetExternalClientInfoOperationCompleted, userState);
        }
        
        private void OnGetExternalClientInfoOperationCompleted(object arg) {
            if ((this.GetExternalClientInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExternalClientInfoCompleted(this, new GetExternalClientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateClientExternalViewAudit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateClientExternalViewAudit(int SearchId, string ExternalClientId, string ModifiedBy, System.DateTime ModifiedDate) {
            this.Invoke("UpdateClientExternalViewAudit", new object[] {
                        SearchId,
                        ExternalClientId,
                        ModifiedBy,
                        ModifiedDate});
        }
        
        /// <remarks/>
        public void UpdateClientExternalViewAuditAsync(int SearchId, string ExternalClientId, string ModifiedBy, System.DateTime ModifiedDate) {
            this.UpdateClientExternalViewAuditAsync(SearchId, ExternalClientId, ModifiedBy, ModifiedDate, null);
        }
        
        /// <remarks/>
        public void UpdateClientExternalViewAuditAsync(int SearchId, string ExternalClientId, string ModifiedBy, System.DateTime ModifiedDate, object userState) {
            if ((this.UpdateClientExternalViewAuditOperationCompleted == null)) {
                this.UpdateClientExternalViewAuditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateClientExternalViewAuditOperationCompleted);
            }
            this.InvokeAsync("UpdateClientExternalViewAudit", new object[] {
                        SearchId,
                        ExternalClientId,
                        ModifiedBy,
                        ModifiedDate}, this.UpdateClientExternalViewAuditOperationCompleted, userState);
        }
        
        private void OnUpdateClientExternalViewAuditOperationCompleted(object arg) {
            if ((this.UpdateClientExternalViewAuditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateClientExternalViewAuditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloChandanCompletedEventHandler(object sender, HelloChandanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloChandanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloChandanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetClientInfoCompletedEventHandler(object sender, GetClientInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetClientSearchInfoCompletedEventHandler(object sender, GetClientSearchInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientSearchInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientSearchInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetExternalClientInfoCompletedEventHandler(object sender, GetExternalClientInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExternalClientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExternalClientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateClientExternalViewAuditCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591